### PR TITLE
Remove operator master jobs from prow

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
this will automerge everything, we need something to block PRs

**Comment by sdake** [comment]
can't we control that in the github UI? I think we don't want any jobs running in master in any event.

**Comment by howardjohn** [comment]
Tide will query for any approved PRs with all tests passing and merge them, so if someone approves on it will merge  Ithink

**Comment by sdake** [comment]
we can remove the approvers when we archive the repo.

**Comment by howardjohn** [comment]
if you have 0 approvers it means anyone can approve AFAIK

**Comment by sdake** [comment]
perhaps @clarketm has an idea how to block prow?

**Comment by howardjohn** [comment]
we used to require some bogus job that doesn't exist: https://github.com/istio/test-infra/blob/cd7c3df726c9e2fc92981e92c3dec25bf84a638d/prow/config.yaml

Could probably do that

**Comment by clarketm** [comment]
> perhaps @clarketm has an idea how to block prow?

Sorry, I do not understand the goal. What is changing with `operator` with how PRs are merged; under what conditions do we want to allow merge now that is changing besides removal of presubmits? We will still have `CODEOWNERS` file and `reviewApprovedRequired` set, so merge is still gated by an approver from `wg-environments-maintainers`. https://github.com/istio/test-infra/blob/830ea2859027294013b5340950a0fba8ca0b7a95/prow/config.yaml#L339

**Comment by sdake** [comment]
> > perhaps @clarketm has an idea how to block prow?
> 
> Sorry, I do not understand the goal. What is changing with `operator` with how PRs are merged; under what conditions do we want to allow merge now that is changing besides removal of presubmits? We will still have `CODEOWNERS` file and `reviewApprovedRequired` set, so merge is still gated by an approver from `wg-environments-maintainers`.
> 
> https://github.com/istio/test-infra/blob/830ea2859027294013b5340950a0fba8ca0b7a95/prow/config.yaml#L339

We do not want PRs to be mergeable  to the operator `master` branch repo in the future as it has been merged into istio/istio, and as such, is archived.

**Comment by clarketm** [comment]
> > > perhaps @clarketm has an idea how to block prow?
> > 
> > 
> > Sorry, I do not understand the goal. What is changing with `operator` with how PRs are merged; under what conditions do we want to allow merge now that is changing besides removal of presubmits? We will still have `CODEOWNERS` file and `reviewApprovedRequired` set, so merge is still gated by an approver from `wg-environments-maintainers`.
> > https://github.com/istio/test-infra/blob/830ea2859027294013b5340950a0fba8ca0b7a95/prow/config.yaml#L339
> 
> We do not want PRs to be mergeable to the operator `master` branch repo in the future as it has been merged into istio/istio, and as such, is archived.

In that case, we can simply deregister `operator` from tide altogether.
https://github.com/istio/test-infra/blob/2a08caaefdfb9ea37b786fd19ad5fd578f0edbe2/prow/config.yaml#L315

**Review by howardjohn — APPROVED** [review]
I think this is the right thing to do. We need the old branches to stick around so removing tide is not right. I am 100% fine with approved PR being merged - all owners understand that the repos have been merged

**Review by clarketm — APPROVED** [review]
@sdake

Please remove the `istio_operator` and `istio_operator_postsubmit` references from [testgrid/default.yaml](https://github.com/istio/test-infra/blob/master/testgrid/default.yaml). Otherwise, this lgtm.

**Pull request closed without merging**
