### PR TITLE
Adds a new image for istio repo for pod-utils

### PR DESCRIPTION
**Pull request by sebastienvas**
Last week I added a new image for pod-utils for the test infra repo. I am updating the test-infra-builder and creating a istio-builder for the istio repo to share duplicate code.

Pod-utils is a new feature in Prow, that take care of the checkout and logs gathering, so the the container only need to care about build and testing.

In a later PR I will update Prow jobs to use this image once https://github.com/istio/istio/pull/8925 is merged.

### CODE REVIEW

**Review by hklai — COMMENTED** [review]
What's the context? And what is this PR supposed to add?

**Comment by sebastienvas** [comment]
I updated the description

**Comment by sebastienvas** [comment]
I ll be testing this with https://github.com/istio/istio/pull/8476

**Review by hklai — APPROVED** [review]
/lgtm

**Pull request merged**
