### PR TITLE
Update docker to ce/new enough to do FROM ... AS and copy --from

### LINKED ISSUE #364: need newer docker
to make layered builds

PR incoming

/assign ldemailly

### PR DESCRIPTION
**Pull request by ldemailly**
Try#2 after #365: Need to switch to CE to get new enough

Pushed gcr.io/istio-testing/prowbazel:0.2.1

```release-note
Switching docker to 17.05.0~ce-0~ubuntu-xenial in order to get FROM ... AS and copy --from
```

Really fixes #364

### CODE REVIEW

**Comment by ldemailly** [comment]
@sebastienvas my first attempt didn't work (latest EE isn't new enough but this one is)

**Review by sebastienvas — APPROVED** [review]

**Comment by ldemailly** [comment]
ty!!!

**Comment by sebastienvas** [comment]
I am seeing this failure in one of the prow job

+ [[ 1000 -ne 0 ]]
+ SUDO=sudo
+ sudo service docker start
/etc/init.d/docker: 103: ulimit: error setting limit (Operation not permitted)

**Comment by nlandolfi** [comment]
which one? link?

**Comment by sebastienvas** [comment]
I filed https://github.com/istio/test-infra/issues/370.

**Pull request merged**
