### PR TITLE
Istio prow: enable secret managed by kubernetes external secrets

### PR DESCRIPTION
**Pull request by chaodaiG**
This was enabled in upstream and working: https://github.com/kubernetes/test-infra/blob/master/prow/prow_secrets.md

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
It would be really nice to have gitops for Secrets as well, something like SealedSecrets. I don't suppose this allows us to do that?

**Comment by chaodaiG** [comment]
> It would be really nice to have gitops for Secrets as well, something like SealedSecrets. I don't suppose this allows us to do that?

Afaict not yet, but I don't see what would be the blocker https://github.com/external-secrets/kubernetes-external-secrets

**Comment by chaodaiG** [comment]
Realized that istio-prow cluster doesn't have workload identity enabled yet, would be good to enable before merging this PR.
/hold

@howardjohn , any objection enabling workload identity in prow cluster?

**Comment by howardjohn** [comment]
Not particularly, unless there are some downsides I don't know of? I assume there should be no issues?

If it will evict pods from the node upgrade though, can we wait until night/weekend? We just cut release branch so we are at peak load on prow right now and don't want to cause issues

**Comment by chaodaiG** [comment]
> Not particularly, unless there are some downsides I don't know of? I assume there should be no issues?
> 
> If it will evict pods from the node upgrade though, can we wait until night/weekend? We just cut release branch so we are at peak load on prow right now and don't want to cause issues

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#limitations, no obvious downside that would affect prow afaict. And yes I believe it will evict pods, so I'll wait until tomorrow before enabling WI on prow

**Review by fejta — APPROVED** [review]

**Comment by fejta** [comment]
We're using this in the other prow instances and it is pretty great.

Any idea when this will be ready for istio?

**Comment by chaodaiG** [comment]
Workload identity was enabled. This PR is now ready to be merged @howardjohn

**Comment by chaodaiG** [comment]
Added prow labels so these can be deployed. @fejta , may I have another stamp please?
/unhold

**Pull request merged**
