### PR TITLE
Add kubeconfig for mixer/presubmit

### PR DESCRIPTION
**Pull request by yutongz**
**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by yutongz** [comment]
fyi @mandarjog @jmuk

**Comment by yutongz** [comment]
@sebastienvas  PTAL Bypassed review to fix mixer presubmit missing kubeconfig.

**Comment by sebastienvas** [comment]
Why was this needed? Are they adding an e2e in mixer?

**Comment by jmuk** [comment]
mixer will start using k8s CRDs for config storage. e2e tests and some of the unit tests will need this.

**Comment by sebastienvas** [comment]
Ok cool! Thanks @yutongz for the quick response.

**Pull request merged**
