### PR TITLE
Mount github token to postsubmits

### PR DESCRIPTION
**Pull request by chxchx**
**Release note**:

```release-note
none
```

### CODE REVIEW

**Review by nlandolfi — APPROVED** [review]
LGTM

One thing I meant to voice before I left is the security semi-concern implicit in mounting credentials to a pod. Hypothetically someone could write a PR that modified a prow job to cat the credential and then steal it...that said I realize we _need_ to mount these.

postsubmit feels safer tho because it only gets run after someone from the org approves it which is a good filter. But for presubmits I've thought about this...thoughts?

cc @sebastienvas

**Comment by chxchx** [comment]
/assign @yutongz
/assign @sebastienvas
PTAL

**Comment by chxchx** [comment]
@nlandolfi I just checked prow cluster config and was surprised to see that we do mount secrets to pod even during presubmit. You are absolutely right about the security concern. I thought about encrypting on our secrets but then malicious users could just cat the key instead. It boils down to the fact that we faithfully execute whatever source code that is given to us in presubmit and that is dangerous. Will definitely followup on this.

**Comment by nlandolfi** [comment]
yeah totally I think when Laurent and I talked about this we decided that it was for the time ok-ish because we don't run code from people not in the org...automatically at least.

**Comment by chxchx** [comment]
[Thompson K. Reflections on Trusting Trust. _Communications of the ACM_. 1984 Aug 1;27(8):761-3.](https://www.ece.cmu.edu/~ganger/712.fall02/papers/p761-thompson.pdf)

**Review by sebastienvas — APPROVED** [review]

**Pull request merged**
