### PR TITLE
Check in a script to upgrade prow

### PR DESCRIPTION
**Pull request by fejta**
/assign @utka @howardjohn 

Usage: `bump.sh [ --auto | v20190703-1f4d61631 | --latest ]`

This will update the images used by prow to match what upstream has deployed (aka latest known working version)

### CODE REVIEW

**Comment by fejta** [comment]
Ugh, build-test failed... Let me debug:

http://prow.istio.io/ -> click the :recycle:  button -> http://prow.istio.io/rerun?prowjob=809b095e-9dc1-11e9-91c7-d6a112a4762e 

I can then futz with the yaml and `kubectl create` the fix until I get a working job (I suspect it has to do with that SSD host mount)

**Comment by howardjohn** [comment]
/lgtm

The bazel change may have broken something on the build though?

**Comment by howardjohn** [comment]
Along those lines of rerunning. If you click "run" you get to http://prow.istio.io/github-login?dest=%2F?rerun=work_in_progress with a 404. Not sure if this is expected to work or not though

**Comment by fejta** [comment]
:rofl: That's a little easter egg of a feature under development https://docs.google.com/document/d/1ykgWeEnh4SwX9AuQz28sicFCpqjuEaYclLVTlStNggg/edit

```console
$ kubectl --context=istio create -f ~/test.yaml 
prowjob.prow.k8s.io/24a2a394-9dc2-11e9-bab9-e2e48a70f8cd created
```

Seems happier: http://prow.istio.io/log?job=build-test&id=799

**Comment by mirandachrist** [comment]
>  That's a little easter egg of a feature under development https://docs.google.com/document/d/1ykgWeEnh4SwX9AuQz28sicFCpqjuEaYclLVTlStNggg/edit
> 
See [this issue](https://github.com/kubernetes/test-infra/issues/13321) for updates on the feature :)

**Pull request merged**
