### PR TITLE
Integration istio/common-files

### PR DESCRIPTION
**Pull request by howardjohn**
Istio has a repo to store common files so things like linting, license,
etc are consistent across repos. This change integrates these files
here.

This also replaces the lint presubmit test with the common linters.

### CODE REVIEW

**Comment by howardjohn** [comment]
our current lint script ignores errors.. let me update this PR with the lint errors fixed before merging

**Review by geeknoid — APPROVED** [review]

**Comment by howardjohn** [comment]
/hold

until I fix lint errors

**Review by fejta — APPROVED** [review]
/hold

**Pull request merged**
