### PR TITLE
Update go.mod for k8s/test-infra

### PR DESCRIPTION
**Pull request by chaodaiG**

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by chaodaiG** [comment]
I think I had ran into a deps problem between boskos and k8s/test-infra, and not sure how to resolve

**Comment by howardjohn** [comment]
@chaodaiG https://github.com/kubernetes/test-infra/pull/20422 may be related?

**Comment by chaodaiG** [comment]
Almost made it work...

Passed `test_test-infra` and `gencheck_test-infra`, but failed `lint_test-infra` with licensing issue:
```
ERROR: Some modules have unrecognized licenses:
  github.com/google/pprof: path '/home/prow/go/pkg/mod/github.com/google/pprof@v0.0.0-20190723021845-34ac40c74b70/third_party/svgpan/LICENSE'
```

edited: updated the error message after pinning

I tried pinning `pprof` version to its original version but it didn't help

**Comment by chaodaiG** [comment]
Had to pin k8s/test-infra to a commit at 01/20/2021 due to indirect dependency caused LICENSE issue, no things are ready to be merged

**Pull request merged**
