### PR TITLE
prowtrans & prowgen docker container missing libs

### PR DESCRIPTION
**Pull request by ghost**
The docker distroless container set to `gcr.io/distroless/static` is missing the libraries necessary for the 
[golang binary to run](https://github.com/GoogleContainerTools/distroless/tree/main/base)

PR to revert back to gcr.io/distroless/base

Running off of static returns an exec error.
```
docker run gcr.io/istio-testing/prowtrans:latest
exec /prowtrans: no such file or directory
```

### CODE REVIEW

**Comment by howardjohn** [comment]
should we instead build a static binary ?

**Comment by ghost** [comment]
> should we instead build a static binary ?

Yes, it should be static. This is changed. Thank you.

**Comment by ericvn** [comment]
@jtischer-acasi Would you please satisfy the CLA requirements. Thanks.

**Review by howardjohn — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
