### PR TITLE
Update Bazel to 0.28.0.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Review by fejta — APPROVED** [review]
/hold 
What produces the images?
Do a /hold cancel when you're ready for it to merge

**Comment by PiotrSikora** [comment]
No idea who/what produces the images. I believe it's a manual step, but I don't have permissions to push the images, so I don't have the details. cc @utka

**Comment by utka** [comment]
/lgtm
I lost permissions to push images as well. I think it can be done by prow on call

**Comment by PiotrSikora** [comment]
So we should cancel the hold and once it's merged we should get prow on-call to build & push the image? I that correct?

**Comment by utka** [comment]
This is my understanding how prow on call works

**Comment by Katharine** [comment]
I've built and pushed [the image](https://gcr.io/istio-testing/prowbazel:0.5.8).

**Comment by fejta** [comment]
This isn't really a prow service. I suspect But we should have access to the `istio-testing`... and while I'm writing this looks like Katharine already did it (thanks!). I suspect she did this by running a command on her workstation (hence why it isn't prow).

Ideally we create postsubmits to build and push these images, like we do for kubernets/test-infra images. Then we can make sure prow is running those correctly. Examples of these jobs:

* Using GCB -- https://github.com/kubernetes/test-infra/blob/7aef384140833379d3e72f33bc0bb9d10770aefe/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L155-L182
* Using bazel -- https://github.com/kubernetes/test-infra/blob/7aef384140833379d3e72f33bc0bb9d10770aefe/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L55-L74

**Pull request merged**
