### PR TITLE
Remove vendor

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Comment by fejta** [comment]
Wow great work! Do things still build with bazel???

**Review by fejta — APPROVED** [review]
/hold

**Comment by fejta** [comment]
Personally I'm a bit sad about not using bazel, but happy to see the million lines of vendor code go away from the repo

**Comment by howardjohn** [comment]
/hold cancel

bazel can't get in the way of my 1 million lines of code stats...

This is mostly the last repo left on bazel though, so it makes sense to go to standard go modules to reduce the complexity of new developers working on test-infra - which I really want to happen

**Comment by duderino** [comment]
> bazel can't get in the way of my 1 million lines of code stats...
> 

Best argument of the year

**Comment by fejta** [comment]
Yeah I initially thought you'd figured out how to remove vendor while still using bazel, and I'm easy to copy this pattern over to kubernetes/test-infra :)

**Pull request merged**
