### PR TITLE
make test-arm optional

### PR DESCRIPTION
**Pull request by zirain**
see ci result: https://github.com/istio/proxy/pull/4728

cc @kyessenov @howardjohn

### CODE REVIEW

**Comment by ericvn** [comment]
I am working on a potential tools update. Unfortunately, building a tools image to test locally takes a while. At least golangci-lint and su-exec have issues with being build on a later Ubuntu version so working to get static versions of those tools generated.

**Comment by zirain** [comment]
test-arm will fails with lint

**Comment by ericvn** [comment]
I'm not so sure of the urgency of getting istio/proxy PRs merging as the updated istio.proxy build still is failing tests to merge into istio/istio. Need to understand those test failures as well.

**Review by howardjohn — APPROVED** [review]
Seems reasonable for me in the short term while we debug/fix

**Pull request merged**
