### PR TITLE
run proxy postsubmit periodically

### PR DESCRIPTION
**Pull request by rkpagadala**
Proxy postsubmit failed twice in the last week, this is a problem because we depend on it to create artifacts used in istio/istio. Running it periodically overcomes this problem

### CODE REVIEW

**Review by hklai — COMMENTED** [review]
should we run all postsubmit periodically?

**Comment by rkpagadala** [comment]
@hklai
 istio postsubmit is a long list and prone to change, we need a better solution for it.
I added istio/api postsubmit as well

**Comment by rkpagadala** [comment]
@hklai PTAL added postsubmits for istio, api and proxy for master branch

**Comment by hklai** [comment]
are these results used to determine green build in release?

**Comment by rkpagadala** [comment]
Not yet. The main motivation has been to run post submit for proxy which generates artifacts for istio build.

**Comment by hklai** [comment]
I think we should eventually move proxy build to istio automation instead.

**Comment by rkpagadala** [comment]
Closing this new PR at https://github.com/istio/test-infra/pull/1030

**Pull request closed without merging**
