### PR TITLE
Avoid creating default gcs client in ProwAccessorMock contructer

### PR DESCRIPTION
**Pull request by chxchx**

### CODE REVIEW

**Review by sebastienvas — APPROVED** [review]

**Comment by sebastienvas** [comment]
I am still seeing an issue:
2018/03/30 21:11:52 ci.go:164: Rerunning istio-postsubmit
2018/03/30 21:11:52 gcsClient.go:42: Failed to create a gcs client, dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by chxchx** [comment]
I had default credentials set up on my desktop so I have not caught this issue in this fix. Please take a look on my other fix to remove actual gcs instance in unit tests https://github.com/istio/test-infra/pull/768

**Pull request merged**
