### PR TITLE
Use clang 5.0 for istio/proxy release-1.0 branch.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
cc @rkpagadala @lizan

**Comment by PiotrSikora** [comment]
@lizan any thoughts on whether we should keep using clang-5.0 on `release-1.0` or upgrade to clang-6.0?

**Comment by lizan** [comment]
I'm less concerned about clang versions to build, since we're already switching from gcc to clang for 1.0 release, right?

**Comment by PiotrSikora** [comment]
@lizan nope, we switched to clang for release builds on `master` branch only.

**Comment by lizan** [comment]
I meant switching from gcc to clang-5.0 is as risky as switching from gcc to clang-6.0, so either is fine if we are going to do either anyway.

**Comment by PiotrSikora** [comment]
@lizan yeah, but we're not switching to either on the `release-1.0` branch ;)

**Comment by kyessenov** [comment]
Piotr, make sure to start a PR on istio to pick up your changes. We cannot
quality whether the build changes are OK unless we run tests end to end.

**Comment by kyessenov** [comment]
E.g. you are not done until you ship it to istio. I had too much "fun"
trying to absorb last changes into istio.

:shipit:

**Pull request merged**
