### PR TITLE
Cleanup gcsweb and velodrome ing object configs: part 2

### PR DESCRIPTION
**Pull request by clarketm**
pre: https://github.com/istio/test-infra/pull/2524

### CODE REVIEW

**Review by fejta — APPROVED** [review]
/hold
/assign @chases2

**Review by fejta — APPROVED** [review]

**Comment by clarketm** [comment]
Hold off on this for now. The previous deploy failed. https://prow.istio.io/view/gcs/istio-prow/logs/deploy-prow_test-infra_postsubmit/47. Either the kubectl version needs to be updated in the image or the prune command needs to be modified. 

prerequisite: 
- [x] https://github.com/istio/test-infra/pull/2551
- [x] Update DNS A records

**Review by fejta — APPROVED** [review]

**Comment by clarketm** [comment]
Updated this to delete the 2 temporary ingress objects now that the permanent ones are active.

**Comment by clarketm** [comment]
DNS A records updated. This is safe to merge.

**Pull request merged**
