### PR TITLE
Update slack invite link

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@kfaseela @craigbox

**Review by craigbox — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
Can we contact to slack to make it not expire

**Review by kfaseela — APPROVED** [review]
Thanks @hzxuzhonghu !

**Comment by craigbox** [comment]
> Can we contact to slack to make it not expire

[Apparently](https://github.com/istio/community/issues/1199#issuecomment-1706191531)!

**Comment by kfaseela** [comment]
> Can we contact to slack to make it not expire

We would need a paid version, which CNCF provides now? I think the migration was already in plan @craigbox ?

**Comment by hzxuzhonghu** [comment]
Migrate to cncf channel? If yes, i donot feel that is friendly, we will lose large number of members

**Comment by kfaseela** [comment]
> Migrate to cncf channel? If yes, i donot feel that is friendly, we will lose large number of members

Looks like @craigbox is suggesting a tip above, may be we should try :)

**Comment by craigbox** [comment]
> Migrate to cncf channel?

steering opinion remains "no"

**Comment by ericvn** [comment]
I thought moving to CNCF left us with a single channel (which we have there today). We lose all ability to have things like release/wg/committee channels, etc.

**Pull request merged**
