### PR TITLE
Cherrypicker: add "cla: yes" label to cherrypicked PRs

### LINKED ISSUE #6333: Cherrypick PRs should not require @googlebot I consent
After a PR from a non-googler is merged, if it includes a cherrypick/release-x.x label, the corresponding cherrypick PR requires a `@googlebot I consent` comment from the contributor(s) of the original PR.

This shouldn't be necessary, since the content has already been checked for CLA conformance in the original PR (i.e., this is just the same change that has already been approved and merged in the master branch).

The bigger problem is that it is often very difficult to get the attention of the original contributor to add the required `@googlebot I consent` comment to allow the PR to merge, resulting in unnecessary delays, and often simply needing to override the process by administrator force merge of the PR.

Here is one of many cherrypick PRs that was force merged because of the desire to have the change appear on istio.io ASAP, but lack of response from the original contributor: https://github.com/istio/istio.io/pull/6328#issuecomment-572772825

### PR DESCRIPTION
**Pull request by clarketm**
dependent on: https://github.com/kubernetes/test-infra/pull/17028
fixes: https://github.com/istio/istio.io/issues/6333

### CODE REVIEW

**Comment by rspier** [comment]
Please only do this if the original PR has `cla: yes`.

**Comment by howardjohn** [comment]
the original pr should not merge if the CLA was not signed, is it still a concern?

**Comment by clarketm** [comment]
> Please only do this if the original PR has `cla: yes`.

Yes, the PR containing the cherrypick will only be created (and labeled) after the original PR is merged which requires the original PR author to sign the CLA (i.e. `cla: yes`) for those commits.

**Comment by chases2** [comment]
/lgtm
/approval
/hold
(for additional reviews)

**Comment by chases2** [comment]
/lgtm
/approve
/hold
(for additional reviews)

**Review by cjwagner — APPROVED** [review]

**Review by fejta — APPROVED** [review]

**Pull request merged**
