### PR TITLE
Add ipv6 tests

### PR DESCRIPTION
**Pull request by aojea**
depends on:

- [x] https://github.com/istio/istio/pull/22070

- [x] https://github.com/istio/tools/pull/800

xref: https://github.com/istio/istio/issues/1756

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
LGTM once the dependencies merge

**Comment by aojea** [comment]
dependencies were merged

**Review by howardjohn — APPROVED** [review]
youll need to run `make generate-config` and check that in as well

**Pull request merged**
