### PR TITLE
Fix the test select flag for istio

### PR DESCRIPTION
**Pull request by ZhengzheYang**
This PR aims to fix the bug described in https://github.com/istio/istio/issues/24909 and https://github.com/istio/istio/pull/24876. Should be reviewed together.

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Why do we need this for istio-1.6.yaml? The new VM stuff is only in master right?

Also we need this for integ-k8s-117, integ-k8s-119 as well right?

**Comment by ZhengzheYang** [comment]
> Why do we need this for istio-1.6.yaml? The new VM stuff is only in master right?
> 
> Also we need this for integ-k8s-117, integ-k8s-119 as well right?

Oh I looked at the log of https://prow.istio.io/view/gcs/istio-prow/logs/k8s-tests_istio.io_release-1.6_postsubmit/57 and I thought it fails because of the VM test. Sorry! I will fix it. The latter 2 doesn't seem to set the test select flag so I didn't touch. https://github.com/istio/test-infra/blob/1ec8984742eb9e80aabb747d1891a87c4245d43a/prow/config/jobs/istio.yaml#L199-L201

**Comment by ZhengzheYang** [comment]
I think integ-k8s-117, integ-k8s-119 will stop failing if https://github.com/istio/istio/pull/24876 is merged since if no test_select flag is given, it will default to run pre-submit jobs, which is the correct behavior.

**Review by howardjohn — APPROVED** [review]
oh didn't realize it was just this one. thanks

**Pull request merged**
