### PR TITLE
Update netrc HOME path

### PR DESCRIPTION
**Pull request by clarketm**
The `build-tools-proxy` image sets `HOME=/home`

### CODE REVIEW

**Review by PiotrSikora — APPROVED** [review]

**Review by brian-avery — APPROVED** [review]

**Comment by PiotrSikora** [comment]
Won't that break `prowbazel` builds (i.e. `release-1.4`)?

**Comment by clarketm** [comment]
> Won't that break `prowbazel` builds (i.e. `release-1.4`)?

Good catch. I forgot that is still active. Yes it will. I will create a new preset for `release-1.4` and update PR.

**Comment by clarketm** [comment]
@brian-avery / @PiotrSikora - PTAL. I retained preset definition for `release-1.4`.

**Comment by brian-avery** [comment]
looks good to me.  Thanks.

**Comment by PiotrSikora** [comment]
LGTM, thanks!

**Pull request merged**
