### PR TITLE
Adds collab branches to branch protection

### PR DESCRIPTION
**Pull request by sebastienvas**

### CODE REVIEW

**Review by geeknoid — APPROVED** [review]

**Comment by ozevren** [comment]
What exactly does this mean? Do we need to run checkin gateways for these branches?

**Comment by quanjielin** [comment]
we're supposed to only touch security folder in collab-gcp-identity for CSM nodeAgent development(not for 1.0) and merge master to that branch every week. May need to add this gateway in the future, for now probably don't want blocking issues in master/pilot slow down the development.

**Comment by sebastienvas** [comment]
@ozevren just removed the test framework branch.
@quanjielin the branch is already protected, I am just syncing the current github configuration to Prow config.

**Pull request merged**
