### PR TITLE
Enable branch protection envoy

### PR DESCRIPTION
**Pull request by clarketm**
fix https://prow.istio.io/view/gcs/istio-prow/logs/ci-test-infra-branchprotector/1168990827033141260

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by fejta — APPROVED** [review]

**Comment by fejta** [comment]
How about we just protect everything except whitelisted things?

**Comment by clarketm** [comment]
> How about we just protect everything except whitelisted things?

What do you mean, exactly? Like the inverse of this configuration?

**Comment by PiotrSikora** [comment]
Can we remove protection for the `master` branch? We sync/push `master` directly from [envoyproxy/envoy-wasm](https://github.com/envoyproxy/envoy-wasm) to [istio/envoy](https://github.com/istio/envoy), since we just mirror that branch, and only do PRs for the released branches.

Alternatively, automatically mirroring the `master` branch from there would also work.

**Comment by clarketm** [comment]
> Can we remove protection for the `master` branch? We sync/push `master` directly from [envoyproxy/envoy-wasm](https://github.com/envoyproxy/envoy-wasm) to [istio/envoy](https://github.com/istio/envoy), since we just mirror that branch, and only do PRs for the released branches.

Sure, I will update then send out PR.

> Alternatively, automatically mirroring the `master` branch from there would also work.

This sounds like a good idea going forward. Creating a job for this should be straightforward; I will look into it.

**Pull request merged**
