### PR TITLE
Make Mixer integration tests not-required.

### PR DESCRIPTION
**Pull request by ozevren**

### CODE REVIEW

**Review by nmittler — APPROVED** [review]
/lgtm

**Comment by kyessenov** [comment]
Is it really that flaky? It looks pretty green to me https://k8s-testgrid.appspot.com/istio-postsubmits-master#integration-k8s-tests

**Comment by ozevren** [comment]
https://k8s-testgrid.appspot.com/istio-presubmits-master
It is around ~20%

Pilot and Security K8s integ tests are optional right now due to high
failure rate.

**Comment by kyessenov** [comment]
@ozevren 
Presubmits are failing because PRs are not passing tests. That's not about the tests, but about the submitted code.

**Comment by nmittler** [comment]
@kyessenov do you know which change broke the test?

**Comment by kyessenov** [comment]
@nmittler 
https://storage.googleapis.com/istio-prow/logs/istio-integ-k8s-tests-master/144/build-log.txt is this a failure I should look at?

**Comment by kyessenov** [comment]
Test setup error: helm install stable/redis failed, setValue=--set usePassword=false,persistence.enabled=false, err: command failed: "Error: error validating \"\": error validating data: field spec.volumeClaimTemplates[0].spec.dataSource for v1.PersistentVolumeClaimSpec is required\n" exit status 1
2019-05-16T18:46:24.659963Z	info	CI	=== FAILED: Setup: 'mixer_policy_ratelimit' (helm install stable/redis failed, setValue=--set usePassword=false,persistence.enabled=false, err: command failed: "Error: error validating \"\": error validating data: field spec.volumeClaimTemplates[0].spec.dataSource for v1.PersistentVolumeClaimSpec is required\n" exit status 1) ===

**Comment by kyessenov** [comment]
I think it's because of old helm?
I have helm version
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
and cannot reproduce the failure.

**Comment by nmittler** [comment]
Here's the error I was seeing in my PR: https://k8s-gubernator.appspot.com/build/istio-prow/pr-logs/pull/istio_istio/14076/integ-mixer-k8s-presubmit-tests-master/145

Yeah, looks like helm is a problem.

**Comment by gargnupur** [comment]
I am also seeing this error in my PR's.. has helm version in our environments changed recently? It used to pass before

**Comment by kyessenov** [comment]
Poking around, it might also be a kubectl version.
Who knows where the docker image is for installing kubectl and helm?
My machine has kubectl 1.14.1 and helm 2.8.2 and they work fine. What do you have @gargnupur ?

**Comment by gargnupur** [comment]
I have kubectl 1.9.2 and helm 2.9.1 and it works fine on my machine

**Pull request merged**
