### PR TITLE
Add new cron job for updating envoyproxy/go-control-plane

### PR DESCRIPTION
**Pull request by jacob-delgado**
In the process of adding this script

### CODE REVIEW

**Comment by jacob-delgado** [comment]
cc @ericvn Modeled this after https://github.com/istio/test-infra/blob/a0fe48a9a8f10784b232fec6c53187cfea3b273b/prow/config/jobs/api.yaml#L23

**Comment by howardjohn** [comment]
Is there something specific about g-c-p? Should we just have something
update all dependencies?

**Comment by jacob-delgado** [comment]
If we could figure out a way to do all does that'd be ideal. I would say updating gcp is more vital to the project since it affects things like envoyfilter.

What do you use to update all of the dependencies? I use some hacky bash to update them.

**Comment by howardjohn** [comment]
go-mod-upgrade but it's interactive - not sure it can be done automatically?

There is of course dependabot but it was kind of annoying when I look ~2
years ago. Not sure if it's improved since then

**Comment by jacob-delgado** [comment]
I've used dependabot. It works works well for monorepos, but would probably creates more problems than it solves for istio.

**Comment by howardjohn** [comment]
regardless of what tool I think once a week updating all deps would be
cool. I am sure we can do it - happy to start with this though. Maybe we
can just make the job "update deps" naming though so we can extend it
though?

**Comment by jacob-delgado** [comment]
ping @howardjohn

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
