### PR TITLE
Add statusreconciler deployment

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Review by cjwagner — APPROVED** [review]
LGTM

**Comment by howardjohn** [comment]
I am not an admin btw so I cannot apply this

**Comment by cjwagner** [comment]
/assign @fejta 
Please `/approve` (and this one too so I can do it myself next time: https://github.com/istio/test-infra/pull/1482).

**Comment by cjwagner** [comment]
> I am not an admin btw so I cannot apply this

https://go.k8s.io/oncall, currently @krzyzacy, can deploy this once it merges (or I can).

**Comment by krzyzacy** [comment]
deployed

**Pull request merged**
