### PR TITLE
Enforce branch protection settings even for admins.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by howardjohn** [comment]
Is there any way to override this if something needs manual merge?

**Comment by geeknoid** [comment]
Yes, admins can still force merge things as before.

Turns out right now, anybody that's an admin is considered effectively as a code owner by GitHub. So if you're an admin and you approve a PR, whether or not you're in CODEOWNERS, GitHub will consider it approved. Flipping this bit will hopefully fix this behavior.

**Comment by howardjohn** [comment]
Interesting
/lgtm

**Review by fejta — APPROVED** [review]
/hold

**Comment by fejta** [comment]
I suspect this will prevent tide from merging correctly in repos that don't have CODEOWNERS, like this one.

**Comment by geeknoid** [comment]
@fejta Why is that?

My reading of the setting says that admins are subject to the normal branch protection rules like normal user, and tide runs as a repo admin so this does affect it. But tide should only ever be merging things that passes all of GitHub's mergability rules, so this should be OK.

**Pull request closed without merging**
