### PR TITLE
Install clang and libc++ from the official releases.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Review by clarketm — APPROVED** [review]

**Comment by PiotrSikora** [comment]
@howardjohn could you build and publish this image? Thank you!

**Comment by clarketm** [comment]
I will build and push. Also, I am creating a `postsubmit` prow job now to do this automatically on changes.

**Comment by PiotrSikora** [comment]
@clarketm perfect, thanks!

**Comment by clarketm** [comment]
Image built and pushed. The PR with job should be out shortly as well.

**Comment by PiotrSikora** [comment]
When you say the PR with job should be out shortly, do you mean updates to jobs to use new probazel images? If so, only `release-1.4` and `master` branches should use it, see: #1956.

**Pull request merged**
