### PR TITLE
Add CI/CD support for ztunnel

### LINKED ISSUE #5: Setup prow tests for ztunnel repo

### PR DESCRIPTION
**Pull request by howardjohn**
Fixes https://github.com/istio/ztunnel/issues/5

~Blocked by https://github.com/istio/tools/pull/2184~

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]
approved, but put up a DNM/hold until you can get the istio/toolls PR done

**Comment by howardjohn** [comment]
@listx ptal. thanks!

**Comment by howardjohn** [comment]
ping @istio/operations-maintainers

**Review by listx — APPROVED** [review]

**Pull request merged**
