### PR TITLE
Shorter gaps between dep propagation

### PR DESCRIPTION
**Pull request by chxchx**
**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by yutongz** [comment]
Pre Submit(including e2e-smoke and pilot-e2e) usually takes 15+12=27 min. 30 min seems to be too ambitious.

**Comment by chxchx** [comment]
As we have spoken offline, the dependency update script avoids creating duplicate PRs by checking an MD5 digest of all dependencies. So the consensus was to do this even more often.

**Comment by yutongz** [comment]
/lgtm
That's pretty good.

**Pull request merged**
