### PR TITLE
Upgrade prow to v20190703-1f4d61631

### PR DESCRIPTION
**Pull request by fejta**
/assign @utka @howardjohn

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
/lgtm

**Comment by fejta** [comment]
/retest

I know you want to pass without me manually messing around! :pray: :pray: :pray:

**Comment by fejta** [comment]
noooooooo

**Comment by fejta** [comment]
```console
$ kubectl --context=istio apply -f prow/cluster
cronjob.batch/branchprotector configured
deployment.extensions/deck configured
service/deck unchanged
deployment.extensions/hook configured
serviceaccount/hook unchanged
role.rbac.authorization.k8s.io/hook unchanged
rolebinding.rbac.authorization.k8s.io/hook unchanged
service/hook unchanged
deployment.extensions/horologium configured
deployment.extensions/needs-rebase configured
service/needs-rebase unchanged
deployment.extensions/plank configured
customresourcedefinition.apiextensions.k8s.io/prowjobs.prow.k8s.io unchanged
deployment.extensions/sinker configured
namespace/test-pods unchanged
deployment.extensions/tide configured
service/tide unchanged
persistentvolume/tot-storage unchanged
persistentvolumeclaim/tot-storage unchanged
deployment.extensions/tot configured
service/tot unchanged
```

**Pull request merged**
