### PR TITLE
Replace prowbazel with build-tools-proxy

### PR DESCRIPTION
**Pull request by bianpengyuan**
Test job succeed: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_proxy/2551/proxy-presubmit-new-builder/1, Switch all jobs to use `build-tools-proxy` image and remove the temporary optional jobs.

cc @PiotrSikora

### CODE REVIEW

**Review by PiotrSikora — CHANGES_REQUESTED** [review]
Did you verify and/or confirm that those work for GKE and private builds? cc @clarketm

**Comment by bianpengyuan** [comment]
@PiotrSikora Sure, will verify it today.

**Comment by clarketm** [comment]
If it is only the image that is different and the test passes in OS it
should work in private GitHub. I can verify this to be certain.

**Comment by bianpengyuan** [comment]
I test with internal gke build pipeline and it works fine.

**Comment by PiotrSikora** [comment]
Can you merge with `master` and apply this to the script from #2092 as well?

**Comment by howardjohn** [comment]
@PiotrSikora that PR doesn't yet apply to proxy `master`, waiting to make sure I didn't accidentally change something that breaks in https://github.com/istio/proxy/pull/2561 then I will make it apply to master

**Comment by PiotrSikora** [comment]
Got it, thanks @howardjohn!

**Review by PiotrSikora — APPROVED** [review]

**Review by clarketm — APPROVED** [review]

**Comment by bianpengyuan** [comment]
@clarketm Any idea why this is not merging?

**Review by howardjohn — APPROVED** [review]

**Comment by clarketm** [comment]
> @clarketm Any idea why this is not merging?

No ... but as I type this it merged
/shrug

**Comment by howardjohn** [comment]
It was not approved by owners

**Comment by clarketm** [comment]
> It was not approved by owners

oh, I thought @PiotrSikora was owner.

**Comment by bianpengyuan** [comment]
@clarketm Thanks! I thought you are the owner :)

**Pull request merged**
