### PR TITLE
update prowbazel to 0.5.2 to use gcc-7/g++-7

### PR DESCRIPTION
**Pull request by yangminzhu**
For https://github.com/istio/proxy/pull/2179

### CODE REVIEW

**Comment by lizan** [comment]
FYI in Envoy we updated to gcc-7 (https://github.com/envoyproxy/envoy/pull/5641/files), so it would be better to align with that.

**Comment by yangminzhu** [comment]
> FYI in Envoy we updated to gcc-7 (https://github.com/envoyproxy/envoy/pull/5641/files), so it would be better to align with that.

Thanks, updated to use gcc-7, will also update the circle-ci to use gcc-7 (https://github.com/istio/proxy/blob/b3e338fd5f861a350163a13f02afa118c3620489/.circleci/Dockerfile#L18) in a follow PR.

**Comment by yangminzhu** [comment]
/assign @icygalz
/assign @sebastienvas
/assign @utka
Could you take a look? This is blocking updating the Istio proxy envoy sha.

**Comment by icygalz** [comment]
you need to push the image first before using it in yaml file. I don't see gcr.io/istio-testing/prowbazel:0.5.2 exists yet.

**Comment by utka** [comment]
Do you have permissions to push 0.5.2 image?

**Comment by yangminzhu** [comment]
@icygalz @utka I don't have the permission to do this, could you help to push this?

**Comment by icygalz** [comment]
Do you mind dividing your changes? Please first merge the changes needed to change the docker image and one of us(@utka or me) will push the new image and then you can merge the yaml file changes?

**Comment by yangminzhu** [comment]
@icygalz Done, I reverted the changes in yaml.

**Comment by icygalz** [comment]
The images have been built and pushed. You can now make the the yaml file changes. Thank you for dividing the changes.

**Pull request merged**
