### PR TITLE
Make build-test pass in official bazel container

### PR DESCRIPTION
**Pull request by fejta**
ref https://github.com/istio/test-infra/issues/1396

/assign @utka @howardjohn 

* Delete `preset-prow-bazel` that only one job used.
* Stop using yaml anchors for this job (not recommended practice)
* Use official bazel image rather than our own
* Add missing yaml dep to bootstrap_test
* Make `bazel test //...` print why jobs failed

```console
$ mkpj --job=build-test --config-path prow/config.yaml --job-config-path prow/cluster/jobs > ~/test.yaml && phaino ~/test.yaml
WARN[0000] empty -github-token-path, will use anonymous github client 
PR Number: 1411
INFO[0002] GetPullRequest(istio, test-infra, 1411)       client=github
INFO[0000] Reading...                                    path=/usr/local/google/home/fejta/test.yaml
INFO[0000] Converting job into docker run command...     job=build-test
local /root/.cache path ("cache-ssd" mount): /tmp/cache
local /path/to/istio.io/test-infra [/usr/local/google/home/fejta/src/gh/test-infra]: $HOME/src/gh/istio-test-infra
"docker" "run" "--rm=true" \
 "--name=phaino-44896-1" \
 "--entrypoint=bazel" \
 "-v" \
 "/tmp/cache:/root/.cache" \
 "-v" \
 "/usr/local/google/home/fejta/src/gh/istio-test-infra:/go/src/istio.io/test-infra" \
 "-v" \
 "/go/src/istio.io/test-infra" \
 "-w" \
 "/go/src/istio.io/test-infra" \
 "--label=prow.k8s.io/refs.pull=1411" \
 "--label=prow.k8s.io/refs.repo=test-infra" \
 "--label=prow.k8s.io/type=presubmit" \
 "--label=created-by-prow=true" \
 "--label=prow.k8s.io/job=build-test" \
 "--label=prow.k8s.io/refs.org=istio" \
 "--label=phaino=true" \
 "launcher.gcr.io/google/bazel:0.26.1" \
 "test" \
 "--config=ci" \
 "//..." 
INFO[0008] Starting job...                               job=build-test
INFO[0008] Waiting for job to finish...                  container=phaino-44896-1 job=build-test
INFO: Elapsed time: 126.591s, Critical Path: 30.24s
INFO: 1195 processes: 1195 processwrapper-sandbox.
INFO: Build completed successfully, 1258 total actions
//boskos/gcp:go_default_test                                             PASSED in 3.2s
//docker/istio_builders/prow_builder/bootstrap:bootstrap_test            PASSED in 2.5s
//prow/config:go_default_test                                            PASSED in 1.6s
//sisyphus:go_default_test                                               PASSED in 1.9s
//toolbox/metrics:go_default_test                                        PASSED in 2.2s
//toolbox/metrics/coverage:go_default_test                               PASSED in 1.2s

Executed 6 out of 6 tests: 6 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build completed successfully, 1258 total actions
INFO[0137] PASS                                          duration=2m17.614358871s job=build-test
INFO[0137] SUCCESS 
```

Includes part of https://github.com/istio/test-infra/pull/1400

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
is there a recommend alternative to anchors other than repeating everything?

**Comment by fejta** [comment]
Anchors are fine so long as everyone is on board with it.

It makes the job defs harder to understand, which makes it harder to get large number of people maintaining them. At least over in k8s land, we tend to favor plain yaml (aka json w/ comments) + go programs to programmatically generate/mutate the jobs. People are willing to edit json and like go

Since this job is essentially unique, I don't see a strong need to use anchors here.

**Comment by howardjohn** [comment]
sgtm, I was just curious if there was another alternative people were using. I agree here it doesn't help at all

**Comment by fejta** [comment]
Job configs are an area of active development. As it's still too verbose. 

A big priority is getting to where job configs live in repo rather than a test-infra one.

**Comment by fejta** [comment]
Maria/John any chance I can get an lgtm on this? 

Would really like to see if I can get the tests in this repo below 5m today.

**Review by howardjohn — APPROVED** [review]
/lgtm

**Comment by fejta** [comment]
woo, ty!

**Pull request merged**
