### PR TITLE
Cherrypicker: enable create-issue-on-conflict

### LINKED ISSUE #2423: Cherrypicker: report issue on failed cherrypick
We often see cherrypicks fail and devs don't notice. It would be nice to create an issue for failed cherrypicks, that way they can be easily tracked. Bonus points if it sets the milestone and priority, but those are Istio specific so that may not be feasible

### LINKED ISSUE #16487: Cherrypicker: create GH issue on failed cherrypick
**What would you like to be added**:

Due to merge conflicts, it is inevitable that a cherrypick will fail. 

**e.g.**: https://github.com/istio/istio/pull/20949
image

While the above GitHub comment reporting on the PR it helpful, it would be beneficial to _additionally_ create a GitHub issue (assigned to the PR author) as a reminder that the cherrypick failed and needs to be performed _manually_.

> We often see cherrypicks fail and devs don't notice. It would be nice to create an issue for failed cherrypicks, that way they can be easily tracked. Bonus points if it sets the milestone and priority, but those are Istio specific so that may not be feasible
> – @howardjohn (https://github.com/istio/test-infra/issues/2423)

**Why is this needed**:
Convenience and user experience (UX). 

/assign

### PR DESCRIPTION
**Pull request by clarketm**
fix kubernetes/test-infra#16487
fix istio/test-infra#2423

> Dependent of Prow version after kubernetes/test-infra#17322 is merged.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
this is awesome! good timing for 1.6

**Comment by clarketm** [comment]
Updated Prow (including cherrypicker), so this is now okay to merge.

/assign @cjwagner @fejta

**Review by fejta — APPROVED** [review]
/hold

**Pull request merged**
