### PR TITLE
1.10 branch

### PR DESCRIPTION
**Pull request by howardjohn**

### CODE REVIEW

**Review by ericvn — APPROVED** [review]
Approval since it has merge held.

**Comment by Monkeyanator** [comment]
Looks like we're generating `build-tools:master` in a lot of places that should be `build-tools:release-1.10`

**Comment by ericvn** [comment]
Found that #3215 made a change where the older `master` image is placed in all the jobs. As a work-around for now, the 5 lines or so were commented out for the run, so only the overall image is updated. Will close this PR and merge changes in another.

**Comment by Monkeyanator** [comment]
Closing in favor of [https://github.com/istio/test-infra/pull/3249](https://github.com/istio/test-infra/pull/3249)

**Pull request closed without merging**
