### PR TITLE
Periodic job to renew GKE clusters

### PR DESCRIPTION
**Pull request by chxchx**

### CODE REVIEW

**Comment by chxchx** [comment]
/hold
Will start this job when ready

**Comment by sebastienvas** [comment]
I just added a PR to not use alpha cluster anymore. Plus the prow service account does not have access to istio-testing anymore I believe.

**Comment by chxchx** [comment]
Yes Seb I saw your PR to disable alpha features too. 

Closing this in favor of https://github.com/istio/test-infra/pull/923

**Pull request closed without merging**
