### PR TITLE
Verify that the release scripts work in istio/proxy presubmits.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by kyessenov** [comment]
I don't think we should be pushing artifacts in pre-submit. The pushed stuff should be only for committed changes after code review.

**Comment by PiotrSikora** [comment]
> I don't think we should be pushing artifacts in pre-submit. The pushed stuff should be only for committed changes after code review.

We're not going to push artifacts in pre-submit, only test that they can be built.

**Comment by PiotrSikora** [comment]
See: https://github.com/istio/proxy/compare/master...PiotrSikora:presubmit-release?expand=1

**Comment by kyessenov** [comment]
Still not following. I don't think we need to test bash scripts. If they don't work, just fix them when you see a failure. We'll never have robust scripts anyways.

**Comment by PiotrSikora** [comment]
We used to have it, but it was removed while retiring CircleCI jobs in istio/proxy#2475.

The release scripts broke postsubmit (i.e. pushing release artifacts) just 3 commits later, which tells me that we need this check after all...

**Comment by PiotrSikora** [comment]
@kuat can we get this in? We used to have it enabled until a few days ago, and it proven to prevent breakages in post-submits, so I don't understand why are you against it now.

**Review by kyessenov — APPROVED** [review]
I don't have a right to approve. There is a security problem that un-authorized PRs will pollute (or override?) artifacts that needs to be addressed.

**Review by howardjohn — APPROVED** [review]

**Comment by PiotrSikora** [comment]
Again, the presubmit job is not pushing any artifacts anywhere.

**Comment by kyessenov** [comment]
OK, but the one thing that I have doubts about in the script PR is whether we can push the artifacts :D

**Comment by PiotrSikora** [comment]
Presubmit jobs don't have the permissions to push anywhere, postsubmit job has.

I think that attackers could explicitly load the permissions using `gcloud auth` (i.e. I don't think it's blocked at the Prow level), but that's not new with this job, it's going to be obvious in the offending PRs and presubmit jobs won't accidentally push artifacts.

**Pull request merged**
