### PR TITLE
Little typo

### PR DESCRIPTION
**Pull request by shazaum**
**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by yutongz** [comment]
@shazaum Thanks for your contribution, could you please sign the CLA by following the instruction above :)

**Comment by shazaum** [comment]
@yutongz So, I need remake this pull request?

**Comment by shazaum** [comment]
now I have the CLA...

**Comment by shazaum** [comment]
test

**Comment by rkpagadala** [comment]
@shazaum Please send your vendor typos upstream, and remove them from this PR
e.g. send your iterator.go to 
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/iterator.go

**Pull request closed without merging**
