### PR TITLE
Support client certificate in kubeconfig

### PR DESCRIPTION
**Pull request by mengqiy**
Added option to support creating a GKE cluster with client certificate enabled.
Support creating kubeconfig using client certificate if it is present.

### CODE REVIEW

**Comment by fejta** [comment]
Seb, can/should this be handled upstream?

**Comment by sebastienvas** [comment]
For now this mason component only exist here.

**Review by sebastienvas — APPROVED** [review]

**Review by clarketm — APPROVED** [review]

**Pull request merged**
