### PR TITLE
Stop proxy from update-deps until it's stable

### PR DESCRIPTION
**Pull request by yutongz**
It seems proxy-presubmit is constantly failing. Since it's holiday season, should we just disable auto-PR for now. I think it created too many useless PRs in proxy repo. WDYT, @rkpagadala

### CODE REVIEW

**Comment by yutongz** [comment]
I am not sure why you "/approve" didn't add the "approved" label, wired.

**Comment by rkpagadala** [comment]
Prow directory has OWNERS file.. thats why see
https://github.com/istio/test-infra/pull/647


( Also until you are back form vacation, no more work, I am not going to comment or approve)

**Comment by yutongz** [comment]
OWNERS files is a hierarchical system. If you are in OWNERS files in this level **or higher level**, you can approve this change.

**Comment by rkpagadala** [comment]
Strange. Clearly not working as intended. Feel free to merge. Also I need merge rights until the team is back.

**Comment by yutongz** [comment]
I can't find the reason why it's not working as expected, but I gave you the admin access in test-infra so that you can hold the house. Hope you don't have to use it :)

**Pull request merged**
