### PR TITLE
Update scripts for shellcheck 0.8

### PR DESCRIPTION
**Pull request by jacob-delgado**

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by jacob-delgado** [comment]
cc @cjwagner We would like to upgrade shell-check used in our docker containers, but this PR being blocked prevents us from doing so. Anything I can do to get this job to work?

**Comment by jacob-delgado** [comment]
cc @chaodaiG can you also take a look at this?

**Comment by chaodaiG** [comment]
`integ-test-authentikos_test-infra` is broken, we should just disable it imo

**Review by chaodaiG — APPROVED** [review]
lgtm

might be better to delete `integ-test-authentikos` in a separate PR

**Pull request merged**
