### PR TITLE
turn on pilot-e2e-smoketest reporting

### PR DESCRIPTION
**Pull request by nlandolfi**
```release-note
NONE
```

### CODE REVIEW

**Comment by nlandolfi** [comment]
Blocked by https://github.com/istio/pilot/pull/946

**Comment by nlandolfi** [comment]
@sebastienvas this is ready now

@kyessenov just merged the job script to master -- so going to turn on the reporting for the e2e smoke test with this PR on seb's approval.

**Review by sebastienvas — APPROVED** [review]

**Pull request merged**
