### PR TITLE
Update common-files on postsubmit

### PR DESCRIPTION
**Pull request by clarketm**
This covers **part 2** (`postsubmit` on https://github.com/istio/common-files repo changes) of: https://github.com/istio/test-infra/issues/1627#issuecomment-552665234

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by clarketm** [comment]
@fejta can you please take a look.

**Review by fejta — APPROVED** [review]
Why is this one coming our way?
/hold

**Comment by clarketm** [comment]
> Why is this one coming our way?

In this case, it is because we own the `tools/` directory where `automator.sh` script lives. The `tools/` dir does not have an explicit codeowner so falls back to the wildcard (*).

**Comment by fejta** [comment]
https://github.com/istio/test-infra/blob/master/CODEOWNERS#L1 -> points to the oncall team, anything specific to istio should not go to prow oncall.

Do we consider this common tooling? If so can we move it into kubernetes/test-infra?

**Comment by clarketm** [comment]
> https://github.com/istio/test-infra/blob/master/CODEOWNERS#L1 -> points to the oncall team, anything specific to istio should not go to prow oncall.
> 
> Do we consider this common tooling? If so can we move it into kubernetes/test-infra?

These are general tools but specific to Istio needs ATM. I will follow up and change the CODEOWNERS. To help me understand desired ownership, only Prow Kubernetes resources and Prow configuration should be owned by our team; all else owned by Istio?

**Pull request merged**
