### PR TITLE
Test PR: DO NOT MERGE

### PR DESCRIPTION
**Pull request by cjwagner**
Testing some things with the Authentikos integration test...
/hold

### CODE REVIEW

**Comment by chaodaiG** [comment]
Might not be related, have you tried using later kind image:
https://github.com/istio/test-infra/blob/45d8b042d1a1bf2b30de4e1e8f4327b1962860ae/authentikos/test/lib.sh#L23

**Comment by chaodaiG** [comment]
> Might not be related, have you tried using later kind image:
> https://github.com/istio/test-infra/blob/45d8b042d1a1bf2b30de4e1e8f4327b1962860ae/authentikos/test/lib.sh#L23

I actually had got some luck with latest kind image, authentikos successfully generated the token

**Comment by cjwagner** [comment]
The following seems to confirm that this is a DNS issue in the kind cluster. https://accounts.google.com/o/oauth2/token is reachable from the ProwJob's test container, but not the kind cluster.
```
Try curling https://accounts.google.com/o/oauth2/token outside kind
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 74.125.195.84...
* TCP_NODELAY set
* Connected to accounts.google.com (74.125.195.84) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
{ [1 bytes data]
* TLSv1.3 (IN), TLS handshake, Unknown (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2381 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [80 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=accounts.google.com
*  start date: May  3 11:26:23 2021 GMT
*  expire date: Jul 26 11:26:22 2021 GMT
*  subjectAltName: host "accounts.google.com" matched cert's "accounts.google.com"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
} [1 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
} [1 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
} [1 bytes data]
* Using Stream ID: 1 (easy handle 0x56300a8c5600)
} [5 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
} [1 bytes data]
> GET /o/oauth2/token HTTP/2
> Host: accounts.google.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{ [1 bytes data]
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
} [5 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
} [1 bytes data]
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{ [1 bytes data]
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{ [1 bytes data]
< HTTP/2 404 
< content-type: text/html
< date: Fri, 04 Jun 2021 18:47:37 GMT
< server: scaffolding on HTTPServer2
< content-length: 0
< x-xss-protection: 0
< x-frame-options: SAMEORIGIN
< x-content-type-options: nosniff
< 
{ [5 bytes data]
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{ [1 bytes data]
* TLSv1.3 (IN), TLS Unknown, Unknown (23):
{ [1 bytes data]
* TLSv1.3 (OUT), TLS Unknown, Unknown (23):
} [1 bytes data]

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host accounts.google.com left intact
Try curling https://accounts.google.com/o/oauth2/token from kind
If you don't see a command prompt, try pressing enter.

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0* Could not resolve host: accounts.google.com
* Closing connection 0
curl: (6) Could not resolve host: accounts.google.com
pod "hello" deleted
pod default/hello terminated (Error)
FAILED
```

**Comment by chaodaiG** [comment]
> > Might not be related, have you tried using later kind image:
> > https://github.com/istio/test-infra/blob/45d8b042d1a1bf2b30de4e1e8f4327b1962860ae/authentikos/test/lib.sh#L23
> 
> I actually had got some luck with latest kind image, authentikos successfully generated the token

Had confirmed that version v1.17.0 had trouble

**Comment by cjwagner** [comment]
Wooo, good call Chao, that seems like it was the main problem. I'll close this and make a PR with the fix. Then we should be able to `/retest` Travis' PR and merge that.

**Pull request closed without merging**
