### PR TITLE
make istio/istio prow silent for now

### PR DESCRIPTION
**Pull request by nlandolfi**

### CODE REVIEW

**Comment by nlandolfi** [comment]
@ldemailly this will silence prow on istio/istio for now, sorry about the funkiness with it reporting.

Seb is working on adding the presubmit job [here](https://github.com/istio/istio/pull/464)

**Review by ldemailly — APPROVED** [review]
ty!

**Comment by ldemailly** [comment]
should the config be per repo btw ?

**Comment by nlandolfi** [comment]
yes it should -- and will *eventually* be . The issue tracking this on the upstream prow project is [here](https://github.com/kubernetes/test-infra/issues/3368)

**Comment by nlandolfi** [comment]
@yutongz PTAL

**Review by yutongz — APPROVED** [review]

**Comment by yutongz** [comment]
LGTM

**Pull request merged**
