### PR TITLE
Update config.yaml

### PR DESCRIPTION
**Pull request by yutongz**
**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by yutongz** [comment]
@rkpagadala approve this.

**Comment by cxuu** [comment]
I thought we wanted to do this with shorter wait period? What is the reason behind such revert?

**Comment by yutongz** [comment]
IIRC, the code didn't successfully skip the same diff, instead it created multiple PRs with the same changes. 

@rkpagadala : Correct me if I am wrong or if you want to add more info :)

**Comment by rkpagadala** [comment]
Yes. For the same diff we got multiple PR's

**Pull request merged**
