### PR TITLE
Remove velodrome

### PR DESCRIPTION
**Pull request by jacob-delgado**
This was removed in kubernetes, see https://github.com/kubernetes/test-infra/issues/16836

We should remove this and velodrome.istio.io should no longer work. This may require work from the operations team.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM but is there an alternative?

**Comment by chaodaiG** [comment]
> LGTM but is there an alternative?

Grafana is a possible alternative, if your team could figure out a way to deal with the AGPLv3 license https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/ which is not encouraged by Google(note that the project for Prow is still under Google).

Our team had migrated to use GKE managed prometheus + Gcloud monitoring solution. @cjwagner , I think we have set this up for Istio right?

**Comment by jacob-delgado** [comment]
What is the purpose of velodrome? I just saw that it was removed in upstream k8s due to a possible security issue.

**Comment by chaodaiG** [comment]
> What is the purpose of velodrome? I just saw that it was removed in upstream k8s due to a possible security issue.

iiuc it's Prow dashboard deprecated in favor of Prometheus + Grafana

**Comment by howardjohn** [comment]
I think it was a prow dashboard implemented by Prometheus and grafana. It
was somewhat useful when it existed but not a big deal

**Comment by howardjohn** [comment]
Actually maybe I don't know what I'm talking about.. I may have been
thinking of monitoring.prow.istio.io. Which is also on old grafana

**Comment by chaodaiG** [comment]
since monitoring.prow.istio.io already exist then this PR LGTM to me

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
