### PR TITLE
Switched merging of upstream changes for 1.9 release to use the 'merge' automator workflow

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Comment by dmitri-d** [comment]
ping @ericvn, @PiotrSikora

**Comment by ericvn** [comment]
Have you tried this command locally to verify that things work correctly?

**Comment by dmitri-d** [comment]
> Have you tried this command locally to verify that things work correctly?

The automator.sh changes? Yes.

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
@dmitri-d I noted that the `pull-test-infra-check-testgrid-config` test has been broken for 3 days or so. I did start a discussion in the #test-and-release channel to see if someone knows how to fix it. It seems to coincide with a prow upgrade.

**Comment by dmitri-d** [comment]
@ericvn: found an example of `DefaultTestGroup` here: https://github.com/kubernetes/test-infra/blob/master/config/testgrids/default.yaml#L4. I might be able to take a look later today or tomorrow. Note there's also a `default_dashboard_tab` in the example which I don't see in our default config: possibly another issue.

**Comment by ericvn** [comment]
@dmitri-d Comments in Slack thread mentioned above and two PRs to fix the problem. Trying to figure out if I can approve and have merge one of them, or we also need the second (requires operations approval) right after.

**Pull request merged**
