### PR TITLE
Benchmark Ztunnel Command

### PR DESCRIPTION
**Pull request by Stevenjin8**
Still WIP. This PR adds a command to run benches which is in https://github.com/istio/ztunnel/pull/561. I'm not sure how to upload artifacts.

I want to have the html generated by criterion be an artifact. Do I ust need to add it to /logs/artifacts/ and it will be automatically uploaded to a GCP bucket?

Also, I can't find a way to create a custom response that shows the results of the tests.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM. I was thinking it would be good to merge `./scripts/benchtest.sh` first but I guess this is optional, so merging early may help you test out the script. So lets merge now

**Comment by MorrisLaw** [comment]
> LGTM. I was thinking it would be good to merge `./scripts/benchtest.sh` first but I guess this is optional, so merging early may help you test out the script. So lets merge now

My recent PR to ztunnel fails because the script does not exist yet: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_ztunnel/571/bench_ztunnel/1673373264027586560

**Comment by howardjohn** [comment]
Ah, this should be presubmit_skipped as well so its run only on demand. @MorrisLaw in the meantime it will _not_ block your PR - its optional, even though its always a bit hard to tell that in the UI.

**Comment by Stevenjin8** [comment]
@howardjohn I am working on the fix.

**Pull request merged**
