### PR TITLE
Enable GKE cert for "prow.istio.io" and remove cert-manager

### LINKED ISSUE #1984: Upgrade cert-manager deployment
Similar issue to Kubernetes Prow instance (kubernetes/test-infra#14944), we should either upgrade or consider an alternative such as [Google-managed SSL certificates](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs) (kubernetes/test-infra#14945).

The current certificate expires: **Thursday, December 19, 2019 at 1:53:08 PM Pacific Standard Time**

### PR DESCRIPTION
**Pull request by clarketm**
> **Note:** as a precautionary measure, this has *already* been tested and deployed.

image

closes #1984

### CODE REVIEW

**Review by fejta — APPROVED** [review]
/hold

**Comment by fejta** [comment]
/assign @bentheelder

Should probably coordinate with oncall

**Comment by clarketm** [comment]
> Should probably coordinate with oncall

I will coordinate with @BenTheElder before unholding.

**Comment by Katharine** [comment]
> Note: as a precautionary measure, this has already been tested and deployed.

Deploying unreviewed configuration changes is not precautionary, and doing so without discussing with oncall is not appropriate. Please avoid doing so in future.

**Comment by clarketm** [comment]
Spoke to @BenTheElder , this is good to unhold. I will cleanup and delete the vestigial `cert-manager` deployment once this goes through.

**Pull request merged**
