### PR TITLE
White list collab branches

### PR DESCRIPTION
**Pull request by sebastienvas**

### CODE REVIEW

**Review by kyessenov — APPROVED** [review]
Would be better to have regex instead of exact names, but this works for now.

/lgtm
/approve

**Comment by sebastienvas** [comment]
@kyessenov I misread the doc, it actually does not work the way I thought it did, it just whilte lists per branch per user. Example of use:
https://github.com/kubernetes/test-infra/blob/master/prow/plugins.yaml#L159

**Comment by sebastienvas** [comment]
Closing as configuration options do not work as is for istio, and bot is too verbose.

**Pull request closed without merging**
