### PR TITLE
Add jobs for 1.11

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Review by ericvn — APPROVED** [review]

**Comment by brian-avery** [comment]
The istio-private jobs are missing. Also this needs changes to testgrid.

**Comment by brian-avery** [comment]
Discussed offline, but this was run as
`go run generate.go branch 1.11`

This is missing
`go run main.go branch 1.11` from https://github.com/istio/test-infra/blob/master/prow/generate-transform-jobs/main.go

**Comment by brian-avery** [comment]
Testgrid should be added here: https://github.com/istio/test-infra/blob/master/testgrid/config.yaml

**Comment by jwendell** [comment]
What does this error mean? How to fix it? It looks like it's an optional job.

**Comment by brian-avery** [comment]
It wants `istio_release-1.11_istio_periodic` added to that testgrid file. That's used for tracking stability of jobs.

**Comment by brian-avery** [comment]
Looking at the job, it's not marked optional -- https://github.com/istio/test-infra/blob/master/prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml

Not entirely sure why GitHub isn't saying required here.

**Review by brian-avery — APPROVED** [review]

**Pull request merged**
