### PR TITLE
Try saving the logs

### PR DESCRIPTION
**Pull request by sebastienvas**
Saving bazel logs

```release-note
none
```

### CODE REVIEW

**Comment by sebastienvas** [comment]
@xiaolanz This needs to be added to all our presubmits :(

**Review by xiaolanz — APPROVED** [review]

**Comment by xiaolanz** [comment]
does --test_output=all flag do the job too?

**Comment by sebastienvas** [comment]
Does it forces test to run sequentially ?

**Comment by xiaolanz** [comment]
I don't think so. I can run it with --features=race  flag. not sure if it's what you mean?

**Comment by sebastienvas** [comment]
ok test_output=streamed, is the one that forces test to run sequentially.
Should we use "errors" ? to only get logs on failed tests ?
https://docs.bazel.build/versions/master/command-line-reference.html

**Comment by xiaolanz** [comment]
if we are not restricted by resource, I prefer printing out logs for succeed tests too. It's easier for debugging when we have a easy to access baseline.

**Pull request merged**
