### PR TITLE
Update go to 1.11, remove use of deps in favor of go mod.

### PR DESCRIPTION
**Pull request by sebastienvas**
- Update goland to 1.11.6
- Update gazelle, go rules, buildtools, docker
- Update vendors with go mode

### CODE REVIEW

**Comment by hklai** [comment]
Is this really needed?

**Comment by sebastienvas** [comment]
Yes, we are using really old version of bazel, deps is deprecated. We were trying to update vendors to be able to upgrade prow, and we failed miserably which is why I started all that.

**Comment by sebastienvas** [comment]
The build failure should go away once we use the image with the newer bazel version.

**Pull request merged**
