### PR TITLE
Update prowbazel in proxy/master and proxy/wasm to 0.5.7.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
@utka @icygalz could one of you build and push this image (or give me access to, since I cannot push right now)? Thanks!

**Comment by icygalz** [comment]
i have done it..
Image create&pushed:
gcr.io/istio-testing/test-infra-builder:v20190627-909f1d0d
gcr.io/istio-testing/prowbazel:0.5.7   (still uploading.. give another 5-10 mins)

**Comment by PiotrSikora** [comment]
@icygalz Thanks!

**Comment by icygalz** [comment]
we also need to update:
https://github.com/istio/test-infra/blob/master/prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml#L2
 right? Can be in different PR

/lgtm

**Comment by PiotrSikora** [comment]
@icygalz I have no idea what that is, really.

**Pull request merged**
