### PR TITLE
add yamllint into image

### PR DESCRIPTION
**Pull request by irisdingbj**
Add yamllint into docker image

### CODE REVIEW

**Comment by ericvn** [comment]
After any requested changes are done, and this PR is approved and merged, would you please create the images and put the name:version back here as a comment so @irisdingbj can work the next PR to have the image used in _master_ so she can add the appropriate tests in Istio/istio that require `yamllint`.

Also, would you like @irisdingbj to test the image against `prow-staging` first?

**Comment by icygalz** [comment]
/lgtm

I doubt this will cause anything bad but let's be safe and try it out on prow-staging first :).

**Comment by icygalz** [comment]
i have pushed the image:
gcr.io/istio-testing/istio-builder:v20190620-39da3cc3

Please double check whether the yamlint is already included in the image.

**Comment by irisdingbj** [comment]
> After any requested changes are done, and this PR is approved and merged, would you please create the images and put the name:version back here as a comment so @irisdingbj can work the next PR to have the image used in _master_ so she can add the appropriate tests in Istio/istio that require `yamllint`.
> 
> Also, would you like @irisdingbj to test the image against `prow-staging` first?

Thanks @ericvn

**Pull request merged**
