### PR TITLE
Prevent fast forwarding stable to commits other than master or its ancestor

### PR DESCRIPTION
**Pull request by chxchx**
**Release note**:

```release-note
none
```

### CODE REVIEW

**Review by sebastienvas — CHANGES_REQUESTED** [review]
I think that does not match the requirement. 
Here is postsubmit file
https://github.com/istio/auth/blob/master/prow/auth-postsubmit.sh

The issue is that I want this to be trigered only from master. with the current change if we create a branch of master today, that statement will not change and the postsbumit will still fastforward stable to the release-0.2. SHA. I think we need to find a way to verify that the SHA is a parent of the HEAD of master.

**Comment by chxchx** [comment]
@sebastienvas PTAL

**Review by sebastienvas — APPROVED** [review]
Thanks for fixing this.

**Pull request merged**
