### PR TITLE
Add racetest to testgrid

### PR DESCRIPTION
**Pull request by howardjohn**
This is our first test using testgrid annotation. If this works we can
add other tests using this method.

@fejta does this work? Or is there some other setup we need to do to process these?

### CODE REVIEW

**Comment by fejta** [comment]
Sadly testgrid annotations are not going to work outside of jobs defined in kubernetes/test-infra right now

**Comment by howardjohn** [comment]
Bummer. What is our best option for this? Its not feasible to manually updating `testgrid/config.yaml`, we make mistakes and forget to add tests there all the time. I was hoping to just set this annotation via https://github.com/istio/test-infra/issues/1471.

**Comment by fejta** [comment]
I would make some autobump logic, so:
* Somehow figure out the canonical set of istio testgroups and dashboards we want, and then output this into one or more `istio-*.yaml` files
* Move all the istio dashboards/test groups into their own files in kubernetes/test-infra
* Have a postsubmit prow job compute these files and then diff them against what is in kubernetes/test-infra
* Send a PR (or update the existing one) whenever they differ

**Pull request closed without merging**
