### PR TITLE
Getting rid run after success in presubmit

### PR DESCRIPTION
**Pull request by icygalz**
This has been tested on prow-staging: https://github.com/istio/istio/pull/14772

### CODE REVIEW

**Comment by utka** [comment]
Do we have enough resources?

**Comment by icygalz** [comment]
Actually each test in master has been doing BUILD and TEST since a couple weeks ago and don't need to do the istio-presubmit.sh anymore. This is the final plug for getting rid run_after_success in master branch! WOOT WOOT!!

**Pull request merged**
