### PR TITLE
Modernize monitoring stack

### PR DESCRIPTION
**Pull request by chaodaiG**
Bringing all the improvements had been made on k8s prow monitoring stack since the istio monitoring stack was created 6 months ago:
- Templated mixins: the differences among different prow instances are all configured in a single file `mixins/lib/config.libsonnet`. Once this is merged, the future improvements made in k8s prow monitoring will be easily applied on istio prow monitoring stack by simply copy/paste files other than this single file
- SLO tracking
- More dashboards
- More alerting rules

For easier code review, this PR had been made in 4 commits:

1. Vendor update. Blindly copy/paste vendor over from k8s/test-infra
1. Mixins/grafana dashboards. Improvements of dashboards
1. Mixins/prometheus. Improvements of prometheus alerts
1. Monitoring stack. Small updates due to changes in 2 and 3

### CODE REVIEW

**Review by e-blackwelder — APPROVED** [review]
/hold

Too big for me to review. But I don't see any issues with the files I looked at. (Note: I didn't review any of the `vendor` files.)

**Comment by chaodaiG** [comment]
Resolved merge conflict after https://github.com/istio/test-infra/pull/3016

@e-blackwelder , would you like to take another look before I unhold?

**Review by e-blackwelder — APPROVED** [review]

**Pull request merged**
