### PR TITLE
add codecov to istio postsubmit

### PR DESCRIPTION
**Pull request by tangiel**

### CODE REVIEW

**Comment by utka** [comment]
why did you change staging ?

**Comment by tangiel** [comment]
Just guessing, honestly. I don't know what staging is for. I just noticed there was a script to copy master to staging. Should I revert it?

**Comment by utka** [comment]
Yes, that would be nice.

**Comment by tangiel** [comment]
I just noticed that the file changed a lot more than I meant it to. Do you want me to revert the entire file, or just the parts that were accidentally changed, thus leaving the codecov postsubmit?

**Comment by utka** [comment]
In description it says add codecove to postsubmit, just have the change which you have

**Comment by utka** [comment]
I think you accidentally deleted newly added tests

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
