### PR TITLE
Separate prow/config.yaml jobs into org/repo/branch

### PR DESCRIPTION
**Pull request by sebastienvas**
I want to wait for https://github.com/kubernetes/test-infra/pull/8466 to be merged before doing this. I also need to update the deployments to pick up the job path.

Please limit your changes to the config

### CODE REVIEW

**Comment by rkpagadala** [comment]
@sebastienvas  Can you add a README for what needs to be done when we add a new branch

**Comment by sebastienvas** [comment]
I will submit this in the morning or in the evening.

**Comment by sebastienvas** [comment]
Note that I already deployed the new jobs and created the new job-config configmap.

**Review by rkpagadala — APPROVED** [review]
/lgtm

**Pull request merged**
