### PR TITLE
Update test-infra to use go1.12.5

### PR DESCRIPTION
**Pull request by icygalz**
Update test-infra to use go1.12.5

### CODE REVIEW

**Review by ericvn — COMMENTED** [review]
I'm not sure if it's required, and it may break things so maybe try in a new commit that one can back out later if needed, but does the go.mod need to be updated for the github.com/bazelbuild/buildtools change? And maybe add github.com/bazelbuild/rules_go and github.com/bazelbuild/buildtools at the correct levels. It may be updating the versions in the _vendor_ directory will break things.

**Comment by icygalz** [comment]
i dont think it matters. Bazel will look into at WORKSPACE information to get the version it needs to use.

**Comment by ericvn** [comment]
@icygalz OK.

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
Part of https://github.com/istio/istio/issues/14420

**Pull request merged**
