### PR TITLE
Update required test for istio

### PR DESCRIPTION
**Pull request by sebastienvas**

### CODE REVIEW

**Review by yutongz — APPROVED** [review]
/lgtm

**Comment by yutongz** [comment]
Just curious, why it failed at first time?

**Comment by chxchx** [comment]
I am all about making Prow tests required in istio presubmits and this PR enforces this on the mergebot, but then there is discrepancy between the github required checks and those enforced by the mergebot. Any plans to also update github setting?

Also just double checking but do forget to re-deploy mungegithub after this change.

**Pull request merged**
