### PR TITLE
Update image for 1.3 tests

### PR DESCRIPTION
**Pull request by richardwxn**
The release test is failing because of older golang verion

### CODE REVIEW

**Comment by howardjohn** [comment]
1.3 is supposed to be on golang 1.12

**Comment by howardjohn** [comment]
what is the test failure?

**Comment by richardwxn** [comment]
> what is the test failure?

@howardjohn Here is the link: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/17642/release-test_istio_release-1.3/83.

This is also why I created this PR: https://github.com/istio/istio/pull/17657/files trying to handle it for golang 1.12.

If 1.3 supposed to use golang 1.12 and my another PR doesn't work for golang 1.12, is there other way to fix that failing test, which is blocking a 1.3 change.

**Comment by howardjohn** [comment]
its because of istio/cni, someone must have merged the golang 1.13 changes
into the release-1.3 branch @sdake @geeknoid @rlenglet?

**Comment by geeknoid** [comment]
The release-1.3 cni branch should not be using the build-tools container, or the recent updates to common-files. Prow is not configured to use build-tools for the release-1.3 branch.

If build system changes to master have been pulled into the release-1.3 branch, I think we need to undo those changes. release-1.3 should only receive minor patch level changes, not tool updates.

**Comment by rlenglet** [comment]
I guess it's me? Cf. https://github.com/istio/cni/pull/174 which I did because https://github.com/istio/test-infra/pull/1790 broke all builds in `release-1.3`.

**Comment by howardjohn** [comment]
fixed in istio, we were checking out cni at master...

**Pull request closed without merging**
