### PR TITLE
Update clang to 6.0.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
Note: if approved, please push the images to GCR, since I don't have permission to do that.

cc @rkpagadala @sebastienvas @lizan

**Comment by PiotrSikora** [comment]
cc @chxchx @fejta

**Comment by rkpagadala** [comment]
@PiotrSikora did you push the docker images?

**Comment by PiotrSikora** [comment]
@rkpagadala I didn't, I don't have permission to do that. [See my previous comment](https://github.com/istio/test-infra/pull/947#issuecomment-412750888).

**Pull request merged**
