### PR TITLE
All istio jobs are on kind now

### PR DESCRIPTION
**Pull request by howardjohn**
@geeknoid this pull in a new license file, but the license does not look right...

### CODE REVIEW

**Comment by geeknoid** [comment]
Yeah, I'm seeing this license file being pulled down in my PR too. I can't repro locally, when I collect the licenses on my system it comes out as LICENSE.

I need to understand this...

**Comment by geeknoid** [comment]
This copyright file comes from the github.com/kubernetes/third_party/forked/godep directory in version 1.13.x and 1.14.x, but not 1.15.x.

Apparently, when I build the test-infra repo through the build-tools container on my Mac, I'm not seeing a dependency on the older k8s repo, so the extra license file isn't brought in. But when building through prow, this older dependency is present and so the license file is pulled in.

It's very worrisome that the CI system is seeing a different set of dependencies than what I'm seeing on my system. The point of using the container to build was to make everything the same.

Anyway, let's go ahead and check this in. I'll figure out why I'm not seeing this dependency when building on my Mac.

**Review by geeknoid — APPROVED** [review]

**Comment by fejta** [comment]
Mac operates oddly with mixed casing. AKA I'm pretty sure it considers `License` and `LICENSE` the same file.

Why is licenses/k8s.io/kubernetes/License copywritten to Keith Rarick (as opposed to the kubernetes authors)?

**Comment by geeknoid** [comment]
I figured out the problem with that license file. There are two license files for the package, one is called LICENSE and the other is License. On the Mac, one overwrites the other due to case folding in the file system. But on Linux they are both preserved.

The solution is to change the mirroring feature of the license linter to have it preserve the full path of the original license file within the generated licenses directory. This'll require another rollout of the common files and container, probably next week.

**Comment by geeknoid** [comment]
@fejta Oh, I thought I was clever and figured this all out, but you had already figured it out hours before :-)

**Review by fejta — APPROVED** [review]

**Comment by fejta** [comment]
Battle scars! 

We had to rename all the `BUILD` files to `BUILD.bazel` because of:

https://github.com/kubernetes/kubernetes/tree/master/build
https://github.com/kubernetes/kubernetes/blob/master/BUILD.bazel

**Pull request merged**
