### PR TITLE
Update sticky lgtm config.

### PR DESCRIPTION
**Pull request by hklai**

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@hklai What's this for? Now we have a risk, if the author update code with potential bug, and without reviewer review again, as the `lgtm` label still there,  the bot merged it.

**Comment by linsun** [comment]
@hzxuzhonghu the bot won't merge till all required tests have passed.  This is an effort to save folks time to keep enter lgtm

**Comment by hklai** [comment]
@hzxuzhonghu @linsun Correct. And this is restricted to istio hackers members only to minimize the risk,

**Pull request merged**
