### PR TITLE
Remove installer master from tide

### PR DESCRIPTION
**Pull request by sdake**

### CODE REVIEW

**Comment by sdake** [comment]
See commentary here prior to merge: https://github.com/istio/test-infra/pull/2276

**Review by howardjohn — APPROVED** [review]

**Comment by clarketm** [comment]
> @sdake: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-test-infra-check-testgrid-config	[cc2cf41](https://github.com/istio/test-infra/commit/cc2cf417da7960c9c0ba156c00fbf7512d2654d7)	[link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2277/pull-test-infra-check-testgrid-config/338)	`/test pull-test-infra-check-testgrid-config`

@sdake - run `make testgrid` and add the testgrid changes to the PR. It should fix the `pull-test-infra-check-testgrid-config` presubmit error.

**Comment by sdake** [comment]
> > @sdake: The following test **failed**, say `/retest` to rerun all failed tests:
> > Test name	Commit	Details	Rerun command
> > pull-test-infra-check-testgrid-config	[cc2cf41](https://github.com/istio/test-infra/commit/cc2cf417da7960c9c0ba156c00fbf7512d2654d7)	[link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2277/pull-test-infra-check-testgrid-config/338)	`/test pull-test-infra-check-testgrid-config`
> 
> @sdake - run `make testgrid` and add the testgrid changes to the PR. It should fix the `pull-test-infra-check-testgrid-config` presubmit error.

After a rebase 

```
sdake@beast-01:~/go/src/istio.io/test-infra$ make testgrid
Building with the build container: gcr.io/istio-testing/build-tools:master-2020-01-27T04-51-23.
Using docker credential directory /home/sdake/.docker.
Using gcr credential directory /home/sdake/.config/gcloud.
Using local Kubernetes configuration /home/sdake/.kube
make: 'testgrid' is up to date.
```

I find this surprising as `testgrid` is a PHONY target...

Cheers
-steve

**Comment by sdake** [comment]
> > > @sdake: The following test **failed**, say `/retest` to rerun all failed tests:
> > > Test name	Commit	Details	Rerun command
> > > pull-test-infra-check-testgrid-config	[cc2cf41](https://github.com/istio/test-infra/commit/cc2cf417da7960c9c0ba156c00fbf7512d2654d7)	[link](https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_test-infra/2277/pull-test-infra-check-testgrid-config/338)	`/test pull-test-infra-check-testgrid-config`
> > 
> > 
> > @sdake - run `make testgrid` and add the testgrid changes to the PR. It should fix the `pull-test-infra-check-testgrid-config` presubmit error.
> 
> After a rebase
> 
> ```
> sdake@beast-01:~/go/src/istio.io/test-infra$ make testgrid
> Building with the build container: gcr.io/istio-testing/build-tools:master-2020-01-27T04-51-23.
> Using docker credential directory /home/sdake/.docker.
> Using gcr credential directory /home/sdake/.config/gcloud.
> Using local Kubernetes configuration /home/sdake/.kube
> make: 'testgrid' is up to date.
> ```
> 
> I find this surprising as `testgrid` is a PHONY target...
> 
> Cheers
> -steve

Docker wasn't running. Makefile didn't detect this.

**Comment by sdake** [comment]
In this PR, I've added testgrid to the `gen` target as well since it is needed on every update.

Cheers
-steve

**Comment by howardjohn** [comment]
I didn't look too much into it but you may need to remove the installer references from testgrid/default.yaml - that file is not generated

**Comment by clarketm** [comment]
@sdake @howardjohn 

I misunderstood the original issue. I suggest removing the `testgrid` target altogether. It is legacy, confusing, and no longer needed since the introduction of [transfigure](https://github.com/istio/test-infra/blob/7105de69e7a7832a4e0a7173ecd2dc61d8144a62/prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml#L75-L103) which sends a generated testrid config PR on postsubmit (https://github.com/kubernetes/test-infra/pull/16006).

If we do want to retain the `testgrid` target (e.g. for debugging or emergency updates), we will need to update to a newer `configurator` version since the Prow config schema has changed. Unfortunately, I think there is a bug (https://github.com/kubernetes/test-infra/issues/16110) in newer versions of configurator where the yaml ordering is non-deterministic, so more reason to drop it from `gen` (or altogether) since it will cause `gen-check` to fail if the file is not byte-equivalent between generation and presubmit.

**Comment by sdake** [comment]
> @sdake @howardjohn
> 
> I misunderstood the original issue. I suggest removing the `testgrid` target altogether. It is legacy, confusing, and no longer needed since the introduction of [transfigure](https://github.com/istio/test-infra/blob/7105de69e7a7832a4e0a7173ecd2dc61d8144a62/prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml#L75-L103) which sends a generated testrid config PR on postsubmit ([kubernetes/test-infra#16006](https://github.com/kubernetes/test-infra/pull/16006)).
> 
> If we do want to retain the `testgrid` target (e.g. for debugging or emergency updates), we will need to update to a newer `configurator` version since the Prow config schema has changed. Unfortunately, I think there is a bug ([kubernetes/test-infra#16110](https://github.com/kubernetes/test-infra/issues/16110)) in newer versions of configurator where the yaml ordering is non-deterministic, so more reason to drop it from `gen` (or altogether) since it will cause `gen-check` to fail if the file is not byte-equivalent between generation and presubmit.

@clarketm perhaps I misunderstand, but bear with me:

The path of least resistance here is to remove the testgrid target. This would imply removing testgrid all-together which I have done in this PR: https://github.com/istio/test-infra/pull/2343. If I understand correctly, this is motivated by the move to transfigure (which I don't know anything about) in the work here: https://github.com/istio/test-infra/blob/7105de69e7a7832a4e0a7173ecd2dc61d8144a62/prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml#L75-L103. Within Istio, historically, and not for good reasons, we have generated configuration that is now subsumed by transfigure's capability to send a PR to change. This permits us to both generate configuraiton output and validate the generated output.

Does transfigure change this check-in-all-the-generated-code philosophy?

In the above PR, I changed the generator code to just not generate annotations. This still polluted some of the code base with testgrid stuff see grep here:

```
grep -r testgrid *
go.sum:github.com/GoogleCloudPlatform/testgrid v0.0.1-alpha.3 h1:xID9Mrq7YTmZejkQpdtjPTL5rN56sSZcoU6l5AUD4Mk=
go.sum:github.com/GoogleCloudPlatform/testgrid v0.0.1-alpha.3/go.mod h1:f96W2HYy3tiBNV5zbbRc+NczwYHgG1PHXMQfoEWv680=
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/istio/istio.istio.release-1.1.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_proxy
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_proxy
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_proxy
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_proxy_postsubmit
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml:      testgrid-dashboards: istio_release-1.4_proxy
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml:      testgrid-dashboards: istio_release-1.4_proxy
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml:      testgrid-dashboards: istio_release-1.4_proxy
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml:      testgrid-dashboards: istio_release-1.4_proxy
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml:      testgrid-dashboards: istio_release-1.4_proxy_postsubmit
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml:      testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio/proxy/istio.proxy.release-1.4.yaml:      testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio/tools/istio.tools.yaml:        testgrid-dashboards: istio_tools
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:  - name: post-istio-test-infra-upload-testgrid-config
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:    run_if_changed: '^(prow/cluster/jobs/.*\.yaml)|(testgrid/default\.yaml)$'
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:      testgrid-dashboards: istio_test-infra_postsubmit
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:      testgrid-alert-email: slchase@google.com
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:        - testgrid/default.yaml
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:    testgrid-create-test-group: "false"
prow/cluster/jobs/istio/test-infra/istio.test-infra.trusted.master.yaml:    testgrid-create-test-group: "false"
prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml:  - name: pull-test-infra-check-testgrid-config
prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml:    run_if_changed: '^(prow/cluster/jobs/.*\.yaml)|(testgrid/default\.yaml)$'
prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml:      testgrid-create-test-group: "false"
prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml:        - testgrid/default.yaml
prow/cluster/jobs/istio/api/istio.api.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_api
prow/cluster/jobs/istio/api/istio.api.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_api
prow/cluster/jobs/istio/api/istio.api.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio/api/istio.api.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_infrastructure
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_infrastructure
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/all-periodics.yaml:    testgrid-dashboards: istio_istio.io
prow/cluster/jobs/all-periodics.yaml:    testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/all-periodics.yaml:    testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml:      testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml:      testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml:      testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml:      testgrid-dashboards: istio_release-pipeline
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml:      testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.1.yaml:      testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-dashboards: istio_release-1.3_release
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-alert-email: istio-oncall@googlegroups.com
prow/cluster/jobs/istio-releases/pipeline/istio-releases.pipeline.release-1.3.yaml:        testgrid-num-failures-to-alert: '1'
toolbox/ci2gubernator/README.md:[Testgrid](https://k8s-testgrid.appspot.com/istio-presubmits)
toolbox/ci2gubernator/README.md:locations on GCS so we could have different panels on testgrid that makes
```

Will be annoying to remove those by hand - just to have this work reverted.

Can you confirm your intent?
Cheers
-steve

**Comment by clarketm** [comment]
> The path of least resistance here is to remove the testgrid target. This would imply removing testgrid all-together which I have done in this PR: #2343. If I understand correctly, this is motivated by the move to transfigure (which I don't know anything about) in the work here:



> . Within Istio, historically, and not for good reasons, we have generated configuration that is now subsumed by transfigure's capability to send a PR to change. This permits us to both generate configuraiton output and validate the generated output.
> Does transfigure change this check-in-all-the-generated-code philosophy?

Historically, the `testgrid` target was used to run [configurator](https://github.com/kubernetes/test-infra/tree/master/testgrid/cmd/configurator) which would read in [testgrid/default.yaml](https://github.com/istio/test-infra/blob/master/testgrid/default.yaml) as well as parse all ProwJob annotations on jobs, then generate [istio.gen.yaml](https://github.com/istio/test-infra/blob/master/testgrid/istio.gen.yaml). Next, a human would manually [PR](https://github.com/kubernetes/test-infra/pull/14156) the generated file to another repo: [kubernetes/test-infra/config/testgrids/istio/gen-config.yaml](https://github.com/kubernetes/test-infra/blob/master/config/testgrids/istio/gen-config.yaml) where  the k8s testgrid configuration resides (because both istio and k8s share the same testgrid instance).

So, `transfigure` basically just automates all the above steps: it runs configurator; generates the `istio.gen.yaml` (in a [fork](https://github.com/istio-testing/test-infra-1/tree/transfigure-branch)); then [PR](https://github.com/kubernetes/test-infra/pull/16006)s the change to [kubernetes/test-infra/config/testgrids/istio/gen-config.yaml](https://github.com/kubernetes/test-infra/blob/master/config/testgrids/istio/gen-config.yaml). As far validation and testing, this is also done by `transfigure` in [`pull-test-infra-check-testgrid-config`](https://github.com/istio/test-infra/blob/5ba7bbe306264194fac8d5090f1f70180bc41a0a/prow/cluster/jobs/istio/test-infra/istio.test-infra.master.yaml#L4-L21) presubmit which runs all tests in [kubernetes/test-infra/tree/master/config/tests](https://github.com/kubernetes/test-infra/tree/master/config/tests). While the tests are not comprehensive and (because of the cross-repo nature of the change) generated file staleness is not explicitly checked, the process will catch *general* testgrid configuration errors (such as missing or duplicated dashboard groups: https://github.com/istio/test-infra/pull/2277/commits/c34333423f95ce217b0b067589e359135549f80e).   

> In the above PR, I changed the generator code to just not generate annotations. This still polluted some of the code base with testgrid stuff see grep here:

We should preserve all source references in this repo related to `testgrid` *except* for the make target and generated file (https://github.com/istio/test-infra/pull/2344) for the reasons described above. If in the future, we want to revive this (such as if istio has its own testgrid instance and colocates config and deployment or if we desitre to perform additional testing on the generated testgrid config itself) then we can.

cc @howardjohn @sdake

**Review by clarketm — APPROVED** [review]
@sdake

Please remove the `istio_installer` and `istio_installer_postsubmit` references from [testgrid/default.yaml](https://github.com/istio/test-infra/blob/master/testgrid/default.yaml). Otherwise, lgtm.

**Pull request closed without merging**
