### PR TITLE
Adding 1.12 prow jobs

### PR DESCRIPTION
**Pull request by stewartbutler**

### CODE REVIEW

**Comment by stewartbutler** [comment]
Not sure I did this right, please review

**Review by ericvn — APPROVED** [review]

**Comment by ericvn** [comment]
Missed that the jobs aren't using the new build image (should have been copied)...

**Comment by ericvn** [comment]
Talked with @stewartbutler and he will make some updates top hopefully not put the old image name on the jobs and rerun.

**Pull request merged**
