### PR TITLE
Update boskos README to reflect latest mason config

### PR DESCRIPTION
**Pull request by clarketm**
Minor semantic updates since `mason-config` has been coalesced into `boskos-config` and is now contained in `resources.yaml` file.

### CODE REVIEW

**Review by fejta — APPROVED** [review]

**Comment by howardjohn** [comment]
@clarketm fyi seems jobs are not starting

**Comment by clarketm** [comment]
@howardjohn
There is an upgrade (kubernetes/test-infra#13980) to the plank component needed that merged just before yesterday’s Prow bump. Working on getting this in asap. Should unblock presubmits, otherwise will revert.

**Pull request merged**
