### PR TITLE
Add force push flag

### PR DESCRIPTION
**Pull request by xiaolanz**
to avoid errors like the following:

2017/09/19 09:43:00 Running command git push --set-upstream origin Istio_Release_0.2.3
2017/09/19 09:43:01 Command output: 
To https://github.com/istio/istio.git
 ! [rejected]        Istio_Release_0.2.3 -> Istio_Release_0.2.3 (non-fast-forward)
error: failed to push some refs to 'https://istio:022f1513d9a65fa75711cf76d5c9b97b9c9c6e8e@github.com/istio/istio.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
2017/09/19 09:43:01 Error during UpdateIstioVersionAfterReleaseTagsMadeOnDeps: command failed: "To https://github.com/istio/istio.git\n ! [rejected]        Istio_Release_0.2.3 -> Istio_Release_0.2.3 (non-fast-forward)\nerror: failed to push some refs to 'https://istio:022f1513d9a65fa75711cf76d5c9b97b9c9c6e8e@github.com/istio/istio.git'\nhint: Updates were rejected because the tip of your current branch is behind\nhint: its remote counterpart. Integrate the remote changes (e.g.\nhint: 'git pull ...') before pushing again.\nhint: See the 'Note about fast-forwards' in 'git push --help' for details.\n" exit status 1
```release-note
none
```

### CODE REVIEW

**Comment by sebastienvas** [comment]
I think we want to make a flag in that case. I don't think we want people to overwrite tags without knowing it. Does it make sense ?

**Review by sebastienvas — CHANGES_REQUESTED** [review]
Could you please make it a flag ? I think the default should be to fail as we are not supposed to re-use tags.

**Comment by xiaolanz** [comment]
@sebastienvas I don't think the failure was caused by flag override. I need to remove all flags manually before retag them. 

 github sometimes give this error due to https://stackoverflow.com/questions/10298291/cannot-push-to-github-keeps-saying-need-merge

We are advised to use -f  in dev flow: https://github.com/istio/istio/blob/master/devel/README.md#committing-changes-to-your-fork

**Review by sebastienvas — APPROVED** [review]

**Comment by sebastienvas** [comment]
got it

**Pull request merged**
