### PR TITLE
Remove circleci from installer repo

### PR DESCRIPTION
**Pull request by howardjohn**
Blocked by https://github.com/istio/installer/pull/415

### CODE REVIEW

**Review by clarketm — APPROVED** [review]

**Comment by howardjohn** [comment]
> @istio-testing istio-testing removed the do-not-merge/work-in-progress label 26 minutes ago

not sure why it decided to do that...

**Comment by howardjohn** [comment]
This just automerged a bunch of broken PRs into the installer because prow removed my do not merge label :confused:

**Comment by clarketm** [comment]
@howardjohn - The logic for the `do-not-merge/work-in-progress` label is based on the title of the PR. The [`(?i)^\W?WIP\W`](https://github.com/kubernetes/test-infra/blob/92fd0214a6cc7d324ade582dad951b4cf04a023a/prow/plugins/wip/wip-label.go#L42) regex prefix is matched against the title. The label gets updated (added or removed) based on the following [PR events](https://github.com/kubernetes/test-infra/blob/92fd0214a6cc7d324ade582dad951b4cf04a023a/prow/plugins/wip/wip-label.go#L75-L80). My guess is that when I approved one of these events must have fired, although it is not clear to me which one.

**e.g.**

| Title  | Mergeable  |
|---|---|
| WIP Remove circleci from installer repo    | No  |
| [WIP] Remove circleci from installer repo    | No   |
| Remove circleci from installer repo    | Yes  |

**Comment by Katharine** [comment]
The label was removed as soon as prow saw it on PR creation, because `WIP` wasn't in the title — it was already removed by the time the PR was approved.

The most GitHub-native way to flag a PR as WIP is to open it as a draft PR, which prevents both prow and also any human from merging it until the draft status is removed. Other than that, either include "WIP" in the title or "/hold" in the body.

**Comment by howardjohn** [comment]
Ah that makes sense. Good to know. Thanks!

**Pull request merged**
