### PR TITLE
Increase cpu/mem for istio/{proxy,envoy}

### PR DESCRIPTION
**Pull request by clarketm**
Higher requests for **istio/proxy** and **istio/envoy** so it gets exclusive access to node.

> Note: this is the current max until quota is increase and node pool is migrated

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
if you request 16 core and the node is 16 cores, I think it may never schedule since there are some daemonsets potentially? I may be wrong here, but if not 15 CPUs should do the trick?

**Review by PiotrSikora — APPROVED** [review]
Thanks!

**Comment by clarketm** [comment]
> if you request 16 core and the node is 16 cores, I think it may never schedule since there are some daemonsets potentially? I may be wrong here, but if not 15 CPUs should do the trick?

I was looking for docs for confirmation but couldn't find any. I will change to `15` to be safe. Thanks. Is this also the case for memory? I will lower that to `55Gi` to be safe as well.

We should know fairly quickly if this is insufficient if the pod is stuck in `pending` state.

**Review by howardjohn — APPROVED** [review]

**Comment by PiotrSikora** [comment]
It doesn't look that those jobs are started anymore, so we probably need to put more than 1 vCPU aside.

**Comment by clarketm** [comment]
> It doesn't look that those jobs are started anymore, so we probably need to put more than 1 vCPU aside.

Yep, the pod is saying insufficient cpu and memory: https://github.com/istio/test-infra/pull/2413

**Pull request merged**
