### PR TITLE
Add integration tests that detect race condition to test-infra

### PR DESCRIPTION
**Pull request by lei-tang**
This PR is for #13341 and depends on the PR https://github.com/istio/istio/pull/13342, which has been merged.

### CODE REVIEW

**Comment by utka** [comment]
Don't you mind adding it as postsubmit first to check that it is not flaky?

**Comment by lei-tang** [comment]
Done: added it as postsubmit first.

**Comment by lei-tang** [comment]
https://github.com/istio/istio/issues/13341

**Pull request merged**
