### PR TITLE
Update k8s.io/test-infra to master

### PR DESCRIPTION
**Pull request by fejta**
* Edit manually in go.mod
* Run scripts/update_deps.sh
* Pass `bazel test //... -- -//vendor/...  -//boskos/gcp/... -//boskos/cmd/...`
* WIP: pass `bazel test //boskos/...` (Seb is working on this)

/cc @howardjohn @sebastienvas

### CODE REVIEW

**Comment by howardjohn** [comment]
/lgtm
but the linter doesn't agree

**Comment by fejta** [comment]
linter: "lbtm, please fix"

working on it..

**Comment by fejta** [comment]
@howardjohn @sebastienvas I have tamed the lint-check beast, ptal

**Pull request merged**
