### PR TITLE
Add owners file for submit-queue

### PR DESCRIPTION
**Pull request by yutongz**

### CODE REVIEW

**Review by sebastienvas — APPROVED** [review]

**Review by nlandolfi — APPROVED** [review]
so this is just for test-infra right?

**Comment by yutongz** [comment]
@nlandolfi  yes, just for this repo. I am using this pr to test submit-queue.

**Comment by yutongz** [comment]
@istio-testing test this

**Comment by yutongz** [comment]
@istio-testing test this

**Comment by yutongz** [comment]
@istio-testing test this

**Comment by yutongz** [comment]
@istio-testing test this

**Comment by yutongz** [comment]
@istio-testing test this

**Pull request merged**
