### PR TITLE
Getting rid of run_after_success for istio/istio master's presubmit

### PR DESCRIPTION
**Pull request by icygalz**
/hold
until the https://github.com/istio/istio/pull/14372 is re-submitted.

### CODE REVIEW

**Comment by icygalz** [comment]
/hold cancel

Postsubmit tests without run_after_success are working as expected. Getting rid of run_after_success on presubmit now :D

**Comment by icygalz** [comment]
/hold

simpleTests presubmit test is broken because of image changes. let's hold off this changes for now.,

**Comment by howardjohn** [comment]
Any chance we could do this on the prow-staging branch and check if it works then move it to master?

**Comment by icygalz** [comment]
sure, i will get it in once go1.12 is tested and pass. I don't want to run both changes at the same time in prow-staging.

**Pull request closed without merging**
