### PR TITLE
Adding a new prow file for collab-galley branch

### PR DESCRIPTION
**Pull request by ozevren**

### CODE REVIEW

**Comment by ozevren** [comment]
@sebastienvas any chance I can bother you for a review?

**Comment by sebastienvas** [comment]
Could you instead copy from master and remove anything that does not apply.
In master we should be using the "decorate: true" which is the way to go
forward.

**Review by sebastienvas — CHANGES_REQUESTED** [review]
Please copy from the master branch and remove tests that don't make sense, as this one is already updated to use podutils (the decorate: true)

**Comment by ozevren** [comment]
Thanks. Will do soon.

**Comment by ozevren** [comment]
ok, updated.

**Comment by ozevren** [comment]
Not sure what else is needed for this to go in.

**Pull request merged**
