### PR TITLE
Install go-junit-report in prowbazel image

### PR DESCRIPTION
**Pull request by chxchx**

### CODE REVIEW

**Comment by sebastienvas** [comment]
Don't you need to update the prow config files as well ?

**Comment by chxchx** [comment]
@sebastienvas 

Yes Seb, I was creating this PR for review before using the image directly. To address your comment I have built and pushed the image and also include update to prow configmap in this PR as well. PTAL.

**Comment by rkpagadala** [comment]
lgtm letting seb let this go through

**Review by sebastienvas — APPROVED** [review]

**Pull request merged**
