### PR TITLE
Making release-test required

### PR DESCRIPTION
**Pull request by icygalz**
https://github.com/istio/istio/issues/13823

### CODE REVIEW

**Comment by ozevren** [comment]
Is the test running properly now?

**Comment by icygalz** [comment]
They look good to me:
https://prow.istio.io/?repo=istio%2Fistio&type=presubmit&job=release-test-release-1.2
https://prow.istio.io/?repo=istio%2Fistio&type=presubmit&job=release-test-master

**Comment by icygalz** [comment]
Actually, do we want to make it required for release-1.1 also?

**Pull request merged**
