### PR TITLE
Bind tester service account to clusteradmin.

### PR DESCRIPTION
**Pull request by myidpt**
Fixes https://github.com/istio/istio/issues/3919.

### CODE REVIEW

**Comment by ldemailly** [comment]
how is this different from
https://github.com/istio/istio/blob/d9a5caea8443b058ab7b689f2a802c9d9afa00d6/prow/cluster_lib.sh#L46-L50

we already had clusteradmin role otherwise nothing at all would have worked (not just CA stuff)

**Comment by sebastienvas** [comment]
That s for the shared cluster. cluster lib is used for provisioned cluster

**Comment by ldemailly** [comment]
eventually we shall split unit tests from tests that require an api server and more
but thanks for this current fix/workaround

**Comment by sebastienvas** [comment]
Yes that's what I want to do to

**Pull request merged**
