### PR TITLE
Add new job for sail operator ci to validate olm deploy of the operator

### PR DESCRIPTION
**Pull request by fjglira**
Adding a new ci job for the Sail Operator project. Is part of the work for this [issue](https://github.com/istio-ecosystem/sail-operator/issues/296)

Depends on: https://github.com/istio-ecosystem/sail-operator/pull/313

### CODE REVIEW

**Comment by sridhargaddam** [comment]
@fjglira you can add the following in the commit message.

Depends on: https://github.com/istio-ecosystem/sail-operator/pull/313

**Review by bmangoen — APPROVED** [review]

**Review by jwendell — APPROVED** [review]
/ok-to-test

**Pull request merged**
