### PR TITLE
Retire the unused tests repo, replace with new cri repo.

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Review by howardjohn — COMMENTED** [review]
Why does CRI have its own repo?

**Review by clarketm — APPROVED** [review]
/hold Prow config changes lgtm

**Comment by geeknoid** [comment]
@howardjohn, please discuss with @rlenglet

**Review by howardjohn — APPROVED** [review]

**Comment by jwendell** [comment]
> Why does CRI have its own repo?
> @howardjohn, please discuss with @rlenglet

What is this repo?

**Pull request merged**
