### PR TITLE
Add "Override Annotations" feature to genjobs

### PR DESCRIPTION
**Pull request by chases2**
Allows a passed argument to inject a set of annotations to every generated job.
Default behavior is to delete all annotations, as before.

Also implements this feature to prevent all generated private jobs from making unused TestGrid groups.

xref #2140

/assign @clarketm @howardjohn

### CODE REVIEW

**Review by clarketm — APPROVED** [review]

**Comment by clarketm** [comment]
@chases2 
Need to run `make gen` to regenerate the jobs, otherwise lgtm. Thanks!

**Comment by chases2** [comment]
Update: `make gen`-generated code added in separate commit.

**Comment by chases2** [comment]
Hey, that list of failures is way shorter! :tada:

One more commit to address those (unrelated) failures

**Review by fejta — APPROVED** [review]
/hold

**Pull request merged**
