### PR TITLE
Update test-infra to use go1.12.5

### PR DESCRIPTION
**Pull request by icygalz**
-  Ran scripts/update_deps.sh

- Manually update "io_bazel_rules_go", "bazel_gazelle" info in the WORKSPACE.

-  ran:
    1.  bazel run //:gazelle -- update-repos -from_file=go.mod
    2.  bazel run //:gazelle -- fix

### CODE REVIEW

**Comment by icygalz** [comment]
/hold
for now..

**Comment by utka** [comment]
What's up with linters?

**Comment by ericvn** [comment]
It seems the files that are getting the `no Go files` lint error are ones removed from _vendor_. One might ask why we are `linking` non-existent files?

**Comment by icygalz** [comment]
abandon this PR for newer PR(#1290) which pass both tests.

**Pull request closed without merging**
