### PR TITLE
bazel build @autogo demo

### PR DESCRIPTION
**Pull request by fejta**
/assign @sebastienvas 

`bazel build -- @autogo//... -@autogo//vendor/...`

### CODE REVIEW

**Comment by sebastienvas** [comment]
looks interesting. I guess I need to delete some of the existing BUILD.  Do is still work after with go_image docker rules ?

**Comment by fejta** [comment]
Why close?

**Comment by fejta** [comment]
Sure if you change the binary target to the autogo target

**Comment by sebastienvas** [comment]
I did not mean to close, just comment :)

**Comment by fejta** [comment]
/hold
/unassign @sebastienvas 
/uncc @sebastienvas @yutongz 


Let me add add autogo to k/test-infra so we have a stable commit. Will reassign at that time

**Comment by fejta** [comment]
There's some additional work that needs to happen before this will pass istio tests

**Comment by fejta** [comment]
planning to get to that at some point if it is still interesting?

**Comment by sebastienvas** [comment]
is this enabled in k8s/test-infra ?

**Comment by fejta** [comment]
Yes, you can `bazel test @autogo//prow/...` but it is not something we're using right now (we check in our build rules right now)

**Comment by sebastienvas** [comment]
The issue here is the workspace format. 

I tried it and it seems that tests using files are failing.

```
$ bazel test @autogo//...
DEBUG: /usr/local/google/home/sebastienvas/.cache/bazel/_bazel_sebastienvas/f4be3f8107083088d06107f59152ae3d/external/io_k8s_test_infra/autogo/def.bzl:18:3: Generating @autogo//... rules for istio.io/test-infra...
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed 257 targets (260 packages loaded).
INFO: Found 251 targets and 6 test targets...
FAIL: @autogo//boskos/gcp:go_default_test (see /usr/local/google/home/sebastienvas/.cache/bazel/_bazel_sebastienvas/f4be3f8107083088d06107f59152ae3d/execroot/com_github_istio_test_infra/bazel-out/k8-fastbuild/testlogs/external/autogo/boskos/gcp/go_default_test/test.log)
FAIL: @autogo//sisyphus:go_default_test (see /usr/local/google/home/sebastienvas/.cache/bazel/_bazel_sebastienvas/f4be3f8107083088d06107f59152ae3d/execroot/com_github_istio_test_infra/bazel-out/k8-fastbuild/testlogs/external/autogo/sisyphus/go_default_test/test.log)
FAIL: @autogo//prow/config:go_default_test (see /usr/local/google/home/sebastienvas/.cache/bazel/_bazel_sebastienvas/f4be3f8107083088d06107f59152ae3d/execroot/com_github_istio_test_infra/bazel-out/k8-fastbuild/testlogs/external/autogo/prow/config/go_default_test/test.log)
INFO: Elapsed time: 47.208s, Critical Path: 12.05s
INFO: 510 processes: 492 linux-sandbox, 18 local.
INFO: Build completed, 3 tests FAILED, 531 total actions
@autogo//toolbox/metrics:go_default_test                                 PASSED in 1.1s
@autogo//toolbox/metrics/coverage:go_default_test                        PASSED in 0.2s
@autogo//toolbox/pkg_check:go_default_test                               PASSED in 0.2s
@autogo//boskos/gcp:go_default_test                                      FAILED in 0.2s
  /usr/local/google/home/sebastienvas/.cache/bazel/_bazel_sebastienvas/f4be3f8107083088d06107f59152ae3d/execroot/com_github_istio_test_infra/bazel-out/k8-fastbuild/testlogs/external/autogo/boskos/gcp/go_default_test/test.log
@autogo//prow/config:go_default_test                                     FAILED in 0.2s
  /usr/local/google/home/sebastienvas/.cache/bazel/_bazel_sebastienvas/f4be3f8107083088d06107f59152ae3d/execroot/com_github_istio_test_infra/bazel-out/k8-fastbuild/testlogs/external/autogo/prow/config/go_default_test/test.log
@autogo//sisyphus:go_default_test                                        FAILED in 0.2s
  /usr/local/google/home/sebastienvas/.cache/bazel/_bazel_sebastienvas/f4be3f8107083088d06107f59152ae3d/execroot/com_github_istio_test_infra/bazel-out/k8-fastbuild/testlogs/external/autogo/sisyphus/go_default_test/test.log
```

**Comment by sebastienvas** [comment]
It is not high priority, as I have a stable bazel build right now, but that could be cool.

**Pull request closed without merging**
