### PR TITLE
 Making mixer test not required since it is flaky.

### PR DESCRIPTION
**Pull request by hklai**

### CODE REVIEW

**Comment by kyessenov** [comment]
May I suggest putting `t.Skip` for the two flaky tests? The other 8 in the suite are not flaky.

**Review by rshriram — APPROVED** [review]

**Comment by rshriram** [comment]
t.skip sounds good. but it will still not be required until we see the tests pass reliably.

**Comment by kyessenov** [comment]
They are a pre-requisite for the daily build. So it's the highest priority to fix them.

**Comment by hklai** [comment]
So far I have not seen failures other than the two.
Let's skip them for now and re-evaluate again later today.
https://github.com/istio/istio/pull/6326

**Pull request closed without merging**
