### PR TITLE
Add branch protections for 1.6

### PR DESCRIPTION
**Pull request by brian-avery**
This PR adds branch protections for Istio 1.6.

### CODE REVIEW

**Review by jacob-delgado — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]
@clarketm does this need to have the branches created first?

**Comment by brian-avery** [comment]
If we don't need to wait for the branches, I'll remove the hold label.

**Comment by howardjohn** [comment]
we don't have approval anyways yet

**Comment by clarketm** [comment]
> @clarketm does this need to have the branches created first?

I am not sure how the api handles this. Worst case it is just an error and the branch is skipped until next run of the periodic.

**Review by clarketm — APPROVED** [review]

**Pull request merged**
