### PR TITLE
Revert "Disable "long-job-names" warning in checkconfig"

### PR DESCRIPTION
**Pull request by clarketm**
Reverts istio/test-infra#2075

### CODE REVIEW

**Review by fejta — APPROVED** [review]
/hold

We don't need this check if you don't want it, I was just trying to make the case for why its there.

**Comment by fejta** [comment]
AKA we added it because we had some outages around excessively long job names.

**Comment by clarketm** [comment]
> AKA we added it because we had some outages around excessively long job names.

Knowing this can prevent fatal errors in Kubernetes with Pod creation, it makes this an *attractive* check. Thanks for providing the background and history.

**Comment by fejta** [comment]
We hopefully by now we've already addressed all the issues -- its why we now put the job name in both a label as well as annotation (the annotation has a longer/no limit), but you never know when something will regress, hence the check

**Pull request merged**
