### PR TITLE
Add test for istio/envoy 1.8 branch

### PR DESCRIPTION
**Pull request by bianpengyuan**

### CODE REVIEW

**Comment by bianpengyuan** [comment]
Can someone give me a pointer about how dashboard file is generated?

**Comment by howardjohn** [comment]
@bianpengyuan I think you manually update `testgrid/default.yaml`. I am fairly sure the `testgrid/istio.gen.yaml` is now dead code and should be removed.

**Review by howardjohn — APPROVED** [review]
BTW - for the other ones there is a `prow/config/cmd/generate.go branch` command that will automatically copy everything over. I think its listed on the release steps. istio/envoy is a bit different though so less important

**Pull request merged**
