### PR TITLE
Add prow jobs for upgrade-downgrade tests, upgrade tests, and downgrade tests

### PR DESCRIPTION
**Pull request by lei-tang**
- Add prow job for upgrade-downgrade test from 1.5 latest to 1.6 latest.
- Add prow job for upgrade test from 1.5 latest to 1.6 latest.
- Add prow job for downgrade test from 1.6 latest to 1.5 latest.
- Add prow job for upgrade-downgrade test from 1.6 latest to master.
- Add prow job for upgrade test from 1.6 latest to master.
- Add prow job for downgrade test from master to 1.6 latest.

### CODE REVIEW

**Review by JimmyCYJ — APPROVED** [review]

**Review by howardjohn — COMMENTED** [review]
why do we need upgrade and downgrade test if we have upgrade+downgrade test? the single ones seem redundant?

**Comment by lei-tang** [comment]
> why do we need upgrade and downgrade test if we have upgrade+downgrade test? the single ones seem redundant?

The upgrade-downgrade test first upgrade then downgrade, which is one of the scenarios. The other two scenarios are upgrade-only and downgrade-only. We want to cover all three scenarios. For example, a user may want to obtain test results (e.g., packet delivery ratio) when only a upgrade or downgrade is conducted.

**Comment by howardjohn** [comment]
Why do we want to test all 3? we should either have 2 scenarios (upgrade, downgrade) or a single combined scenario (upgrade the downgrade).What value do we get from having both? To me it seems redundant

**Comment by lei-tang** [comment]
> Why do we want to test all 3? we should either have 2 scenarios (upgrade, downgrade) or a single combined scenario (upgrade the downgrade).What value do we get from having both? To me it seems redundant

One of the values of testing all three scenarios (i.e., upgrade-then-downgrade, upgrade-only, downgrade-only) is that a user may try any one of these three scenarios and want to know the results through the corresponding test.

**Comment by howardjohn** [comment]
Who is the user? An Istio developer or a normal istio user? I have never seen a normal user looking at these tests

**Comment by howardjohn** [comment]
I have also not seen any case where we duplicate our tests

**Comment by lei-tang** [comment]
Per review comments, the tests for the upgrade-downgrade scenario are removed.

**Review by clarketm — APPROVED** [review]
I think we will also need to increase the resource count in boskos config: 
https://github.com/istio/test-infra/blob/9e54f15c64a9a4e8a9a96d162547107677b50bf6/boskos/resources.yaml#L5-L6 

but I will do that in a follow-up.

**Comment by clarketm** [comment]
> Per review comments, the tests for the upgrade-downgrade scenario are removed.

@lei-tang it looks like you forgot to remove the `upgrade-downgrade` tests. If you still plan to remove these as redundant, please do so in a follow-up PR.

**Comment by lei-tang** [comment]
@clarketm Thanks! https://github.com/istio/test-infra/pull/2656 is created to remove the tests for the upgrade-downgrade scenario.

**Pull request merged**
