### PR TITLE
Run istio/istio presubmit on all branches.

### PR DESCRIPTION
**Pull request by nlandolfi**
Addresses a concern raised in https://github.com/istio/test-infra/issues/277
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by nlandolfi** [comment]
@yutongz try lgmt-ing this?

**Review by sebastienvas — APPROVED** [review]

**Comment by yutongz** [comment]
@sebastienvas  For now, please manually add approve label when you want a final approve and make it merge by submit-queue

**Comment by nlandolfi** [comment]
@istio-testing bazel test this

**Pull request merged**
