### PR TITLE
Switch plank to prow-controller-manager in monitoring

### PR DESCRIPTION
**Pull request by fejta**
/assign @chaodaiG

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by chaodaiG** [comment]
Generally looks good, do you also need to change https://github.com/istio/test-infra/blob/b5ae7b85c53553d9c72bae9a74a8a8e5a3c8bfcd/prow/cluster/monitoring/mixins/grafana_dashboards/plank.jsonnet#L24 like https://github.com/kubernetes/test-infra/blob/b26249a6701709bb553ffe14cb3a3c4ee1ae95ab/config/prow/cluster/monitoring/mixins/grafana_dashboards/plank.jsonnet#L26?

**Comment by fejta** [comment]
Done

**Review by chaodaiG — APPROVED** [review]

**Pull request merged**
