### PR TITLE
make racetest required in master branch

### LINKED ISSUE #9053: Should make ciecleci `racetest` required
`Test_KubeSecretController ` failed https://circleci.com/gh/istio/istio/202774?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I am not sure since when it occur. But I can look into and fix it. After that make `racetest` required.

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
fixes: https://github.com/istio/istio/issues/9053

### CODE REVIEW

**Comment by hklai** [comment]
Let's make it required after it becomes stable/green for a few days.
https://k8s-testgrid.appspot.com/istio-presubmits#circleci-racetest

**Comment by hzxuzhonghu** [comment]
ok

**Comment by hklai** [comment]
racetests had started failing again last week.
https://k8s-testgrid.appspot.com/istio-presubmits#circleci-racetest

**Comment by hzxuzhonghu** [comment]
@hklai It is a new case `Test_KubeSecretController`, which was introduced days ago I think. Let me have a look.

So this pr is a urgent if we want no a new case failure.

**Comment by ymesika** [comment]
@hklai `racetest` has been steadily green in the past week. Please consider making it required test now.

**Comment by hklai** [comment]
@ymesika OK let's go for it. Please rebase and resolve conflict, and then I will lgtm.

**Comment by hzxuzhonghu** [comment]
done

**Review by hklai — APPROVED** [review]
/lgrm

**Comment by ymesika** [comment]
@hklai lgrm won't work :)

**Comment by ymesika** [comment]
@hklai please wait with lgtm for https://github.com/istio/istio/pull/9797

**Comment by hklai** [comment]
Ping for update.

I see https://github.com/istio/istio/pull/10036 had been merged, but https://testgrid.k8s.io/istio-presubmits#circleci-racetest is not as green as we would like.

**Comment by hzxuzhonghu** [comment]
@hklai Maybe other prs introduced race again. We should fix them one by one.

**Comment by ymesika** [comment]
@duderino @utka Racetest has been pretty stable on `release-1.1` and `master` for some time now.
Except PR that broke it because it got ignored due it being optional.

Can we merge this please to make it required now?

**Pull request closed without merging**
