### PR TITLE
Revert "Switch this repo from OWNERS to CODEOWNERS (#1625)"

### PR DESCRIPTION
**Pull request by fejta**
This reverts commit c5dc5538feff1871f88f4524e6d683adfa5901f9.

Please merge manually
/assign @howardjohn @geeknoid

### CODE REVIEW

**Comment by howardjohn** [comment]
What was broken?

Interestingly I don't have write access to this repo so despite being an owner i cannot approve this

**Comment by geeknoid** [comment]
Why  revert this PR? Please explain

/hold

**Comment by fejta** [comment]
Nothing in this repo will merge. The previous PR conflated too much stuff that belong in separate PRs

**Comment by geeknoid** [comment]
See https://github.com/istio/test-infra/pull/1658

**Comment by geeknoid** [comment]
#1658  fixed tide.

**Pull request closed without merging**
