### PR TITLE
Bump KES from 6.4.0 to 8.5.1

### PR DESCRIPTION
**Pull request by cjwagner**
Hoping to help with https://github.com/istio/test-infra/issues/3750
/assign @listx

### CODE REVIEW

**Review by e-blackwelder — APPROVED** [review]

**Comment by listx** [comment]
@howardjohn Hi Howard, any idea why I am not `/assign`-able here? I am in both https://github.com/istio/community/blob/master/org/members.yaml and https://github.com/istio/community/blob/master/org/teams.yaml.

**Comment by howardjohn** [comment]
I think you did not accept the invite

**Comment by listx** [comment]
I just joined it, thanks!

**Comment by listx** [comment]
And also apologies for calling you by your last name. Thanks again John!

**Pull request merged**
