### PR TITLE
update container image for api job

### PR DESCRIPTION
**Pull request by jasonwzm**

### CODE REVIEW

**Comment by jasonwzm** [comment]
@howardjohn has the linter been flaky for this repo in the past?

**Comment by howardjohn** [comment]
Its a new issue, its some issue with links. I think our link linting is a really really bad idea. I am going to open an issue about this

**Comment by jasonwzm** [comment]
gotcha! Thanks. Is retry the only workaround for now?

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
