### PR TITLE
Install libc++ in istio-builder images.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Review by duderino — APPROVED** [review]

**Comment by PiotrSikora** [comment]
Note: it's using new `install-libcxx.sh` instead of the existing `install-clang.sh`, to avoid installing LLVM and Clang in the image, but I'm happy to switch to `install-clang.sh` if that's preferred.

**Comment by PiotrSikora** [comment]
Note: we only need this change for the images used to build `release-1.1` and `release-1.2` branches, where we need libc++-7 instead of libc++-8.

**Review by howardjohn — APPROVED** [review]
thanks, I'll build and update tomorrow if someone doesn't before then

**Comment by howardjohn** [comment]
@PiotrSikora when you say this is only needed on 1.1 and 1.2 does that mean we cannot use this for 1.3 or we just don't need it for 1.3?

**Comment by PiotrSikora** [comment]
@howardjohn we don't need it, and it's non-issue if it's in the image.

**Review by clarketm — APPROVED** [review]

**Pull request merged**
