### PR TITLE
Add release-1.4 branch protection

### PR DESCRIPTION
**Pull request by howardjohn**
Do not merge until we create the branches

### CODE REVIEW

**Comment by howardjohn** [comment]
Release branches create, this is needed now

**Comment by howardjohn** [comment]
Note to future: I think the correct move is merging this then creating the branches

**Review by clarketm — APPROVED** [review]
FYI, I renamed the PR and added `WIP` to ensure the `wip` label does not get removed. Rename or remove label when you are ready to merge.

---

Also, I fixed `branchprotector` to continue when it encounters an error #1511, so I also think the correct move is merging this then creating the branches.

**Pull request merged**
