### PR TITLE
[WIP] Update 1.2 prow jobs to use new Golang 1.12 and bazel 0.26.0 updates

### PR DESCRIPTION
**Pull request by ericvn**
Wait to verify these changes in `master` before merging for `release1.2`

### CODE REVIEW

**Comment by ericvn** [comment]
FYI: https://github.com/istio/istio/issues/14420

**Comment by ericvn** [comment]
Need to update to the current images used in master (include kind).

**Comment by duderino** [comment]
This very much needs to be approved by one of the 1.2 release managers.  @fpesce @linsun

**Comment by ericvn** [comment]
@duderino I agree 100% that the release managers have to approve this before even thinking about putting it in. The PR was created to hold a set of changes if they decided to do move release 1.2 builds and prow test to Golang 1.12. The problem with the PR as it sits today, is that the images that are called out don't really point to Golang 1.12 images as we found out in master last week (the image was reverted back to Golang 1.10). My comment earlier was to make this PR at least point to something that is correct, in the case that this PR was used (merged or re-opened (if closed which will likely happen after I make the update) and merged). I will make the updates later today and will then close the PR.

**Comment by ericvn** [comment]
Closing for now. If this PR is used, please verify that the images used updated to match master (the current set matches what was used in master around the second week of June 2019).

**Pull request closed without merging**
