### PR TITLE
Add self to CODEOWNERS for top-level infra

### PR DESCRIPTION
**Pull request by clarketm**
Adding myself to top-level `CODEOWNERS` to be able to approve version bumps #1650, configuration, and general infrastructure features.

### CODE REVIEW

**Review by fejta — APPROVED** [review]

**Review by howardjohn — APPROVED** [review]

**Comment by fejta** [comment]
Travis can you close and reopen the PR? I think Google's CLA bot missed the webhook or something

**Comment by fejta** [comment]
Alternatively try leaving a comment first

**Review by geeknoid — APPROVED** [review]

**Comment by clarketm** [comment]
Commenting and close/reopen did not seem to do the trick. @fejta - any other suggestions? I can try new PR.

**Comment by fejta** [comment]
I don't know what it's deal is. I'm having the same issue on another pr. Maybe try opening a new one?

**Comment by fejta** [comment]
Hmm, that's odd

**Comment by howardjohn** [comment]
I triggered it manually at https://github.corp.google.com/prinfo?q=http://github.com/istio/test-infra/pull/1661 @fejta

**Comment by fejta** [comment]
oh neat, thanks didn't know about that!

**Pull request merged**
