### PR TITLE
add sds e2e test to test-infra

### PR DESCRIPTION
**Pull request by quanjielin**
https://github.com/istio/istio/issues/9035

### CODE REVIEW

**Comment by quanjielin** [comment]
@hklai, after submit, the new test will be shown in istio/istio presubmit test immediately or is there any other change/deploy need to be made ?

**Comment by sebastienvas** [comment]
They should be added automatically after sometime.

**Review by hklai — COMMENTED** [review]
Do you want to add it to postsubmit as well?

**Comment by quanjielin** [comment]
added to postsubmit, PTAL, thanks !

**Review by hklai — APPROVED** [review]
/lgtm

**Pull request merged**
