### PR TITLE
enable sds e2e test in master branch

### PR DESCRIPTION
**Pull request by quanjielin**
similar change was made to 1.1 branch in https://github.com/istio/test-infra/pull/1143, add in master presubmit with master reopen

### CODE REVIEW

**Comment by utka** [comment]
@sebastienvas. Can it be this change #1156?

**Comment by hklai** [comment]
I suspect so too. Prob need to clean up those lint errors as a follow up.

**Comment by sebastienvas** [comment]
no this passed before. This related to the fact we use the latest v2 version of gometalinter. So bascially the linting guideline changed after a new version of gometalinter was pushed. We need to update the code.

**Pull request merged**
